unit NWSComps_IOFormat_Const;

interface

const

  IOFORMAT_CONST_CLASSVERSION_MAJOR = 1;
  IOFORMAT_CONST_CLASSVERSION_MINOR = 0; 

  IOFORMAT_CONST_CLASSSIGNATURE = 'TIOFormatHandler';

  IOFORMAT_CONST_TAG_ANSISTRING_NCHARS_START = '<ANSISTRING_NCHARS_START>';
  IOFORMAT_CONST_TAG_ANSISTRING_NCHARS_END = '<ANSISTRING_NCHARS_END>';

  IOFORMAT_CONST_TAG_HEADER_START = '<<HEADER_GENERAL_START>>';
  IOFORMAT_CONST_TAG_HEADER_END = '<<HEADER_GENERAL_END>>';

  IOFORMAT_CONST_TAG_CLASSSIGNATURE_START = '<<CLASSSIGNATURE_START>>';
  IOFORMAT_CONST_TAG_CLASSSIGNATURE_END = '<<CLASSSIGNATURE_END>>';

  IOFORMAT_CONST_TAG_CLASSVERSIONMAJOR_START = '<<CLASSVERSION_MAJOR_START>>';
  IOFORMAT_CONST_TAG_CLASSVERSIONMAJOR_END = '<<CLASSVERSION_MAJOR_END>>';

  IOFORMAT_CONST_TAG_CLASSVERSIONMINOR_START = '<<CLASSVERSION_MINOR_START>>';
  IOFORMAT_CONST_TAG_CLASSVERSIONMINOR_END = '<<CLASSVERSION_MINOR_END>>';

  IOFORMAT_CONST_TAG_SIGNATURE_START = '<<SIGNATURE_START>>';
  IOFORMAT_CONST_TAG_SIGNATURE_END = '<<SIGNATURE_END>>';

  IOFORMAT_CONST_TAG_VERSIONMAJOR_START = '<<VERSION_MAJOR_START>>';
  IOFORMAT_CONST_TAG_VERSIONMAJOR_END = '<<VERSION_MAJOR_END>>';

  IOFORMAT_CONST_TAG_VERSIONMINOR_START = '<<VERSION_MINOR_START>>';
  IOFORMAT_CONST_TAG_VERSIONMINOR_END = '<<VERSION_MINOR_END>>';


implementation

end.
