unit NWSComps_ThumbsBrowser_RES_CONST;

interface
   const

  IDRS_TBSORTZERO = 1000;
  IDRS_TBSORT_NameA = IDRS_TBSORTZERO + 1;
  IDRS_TBSORT_NameD = IDRS_TBSORTZERO + 2;
  IDRS_TBSORT_DateA = IDRS_TBSORTZERO + 3;
  IDRS_TBSORT_DateD = IDRS_TBSORTZERO + 4;
  IDRS_TBSORT_ExifDateA = IDRS_TBSORTZERO + 5;
  IDRS_TBSORT_ExifDateD = IDRS_TBSORTZERO + 6;
  IDRS_TBSORT_SizeA = IDRS_TBSORTZERO + 7;
  IDRS_TBSORT_SizeD = IDRS_TBSORTZERO + 8;
  IDRS_TBSORT_FolderA = IDRS_TBSORTZERO + 9;
  IDRS_TBSORT_FolderD = IDRS_TBSORTZERO + 10;
  IDRS_TBSORT_FileTypeA = IDRS_TBSORTZERO + 11;
  IDRS_TBSORT_FileTypeD = IDRS_TBSORTZERO + 12;
  IDRS_TBSORT_NameNaturalA = IDRS_TBSORTZERO + 13;
  IDRS_TBSORT_NameNaturalD = IDRS_TBSORTZERO + 14;
  IDRS_TBSORT_FolderNaturalA = IDRS_TBSORTZERO + 15;
  IDRS_TBSORT_FolderNaturalD = IDRS_TBSORTZERO + 16;

  IDRS_METAHLPZERO = 1100;
  IDRS_METAHLP_Index = IDRS_METAHLPZERO + 1;
  IDRS_METAHLP_Field = IDRS_METAHLPZERO + 2;
  IDRS_METAHLP_ErrorParsingWrongGridFormat = IDRS_METAHLPZERO + 3;

  IDRS_METAPNZERO = 2000;
  IDRS_METAPN_DISPLAYMODE_NONEMPTY = IDRS_METAPNZERO + 1;
  IDRS_METAPN_DISPLAYMODE_All = IDRS_METAPNZERO + 2;
  IDRS_METAPN_DISPLAYMODE_GROUPED = IDRS_METAPNZERO + 3;
  IDRS_METAPN_PENDINGCHANGES_SINGLE = IDRS_METAPNZERO + 4;
  IDRS_METAPN_PENDINGCHANGES_MULTI = IDRS_METAPNZERO + 5;
  IDRS_METAPN_TABCOMMON = IDRS_METAPNZERO + 6;

  IDRS_SH_OPZERO = 3000;
  IDRS_SH_OP_DELETINGFILES = IDRS_SH_OPZERO + 1;
  IDRS_SH_OP_RECYCLINGFILES = IDRS_SH_OPZERO + 2;
  IDRS_SH_OP_MOVINGFILES = IDRS_SH_OPZERO + 3;
  IDRS_SH_OP_COPYINGFILES = IDRS_SH_OPZERO + 4;
  IDRS_SH_OP_SAVINGFILES = IDRS_SH_OPZERO + 5;
  IDRS_SH_OP_CORRECTINGORIENTATION = IDRS_SH_OPZERO + 6;
  IDRS_SH_OP_ROTATINGFILES = IDRS_SH_OPZERO + 7;
  IDRS_SH_OP_WARNING_RECYCLE_NOTALLOWED_WPD = IDRS_SH_OPZERO + 8;
  IDRS_SH_OP_WARNING_RECYCLE_NOTALLOWED_WIA = IDRS_SH_OPZERO + 9;
  IDRS_SH_OP_WARNING_INTERNETFILE_CANNOTBEMOVED = IDRS_SH_OPZERO + 10;


  IDRS_INFOFORMZERO = 4000;
  IDRS_INFOFORM_FDate = IDRS_INFOFORMZERO + 1;
  IDRS_INFOFORM_FSize = IDRS_INFOFORMZERO + 2;
  IDRS_INFOFORM_HINT_ADDEXIFINFO = IDRS_INFOFORMZERO + 3;
  IDRS_INFOFORM_HINT_ADDIPTCINFO = IDRS_INFOFORMZERO + 4;
  IDRS_INFOFORM_ERROR_CANNOTWRITEMETA = IDRS_INFOFORMZERO + 5;
  IDRS_INFOFORM_BTNSAVE = IDRS_INFOFORMZERO + 6;
  IDRS_INFOFORM_BTNSAVERENAME = IDRS_INFOFORMZERO + 7;
  IDRS_INFOFORM_BTNRENAME = IDRS_INFOFORMZERO + 8;
  IDRS_INFOFORM_BTNADDEXIF = IDRS_INFOFORMZERO + 9;
  IDRS_INFOFORM_BTNADDIPTC = IDRS_INFOFORMZERO + 10;


  IDRS_CAPZERO = 5000;
  IDRS_CAP_SHOWFILENAME = IDRS_CAPZERO + 1;
  IDRS_CAP_SHOWFILEDATE = IDRS_CAPZERO + 2;
  IDRS_CAP_SHOWFILESIZE = IDRS_CAPZERO + 3;
  IDRS_CAP_SHOWFILEDIMS = IDRS_CAPZERO + 4;
  IDRS_CAP_SHOWEXIFDATETIME = IDRS_CAPZERO + 5;
  IDRS_CAP_SHOWEXIFAUTHOR = IDRS_CAPZERO + 6;
  IDRS_CAP_SHOWEXIFTITLE = IDRS_CAPZERO + 7;
  IDRS_CAP_SHOWEXIFSUBJECT = IDRS_CAPZERO + 8;
  IDRS_CAP_SHOWEXIFCOMMENT = IDRS_CAPZERO + 9;
  IDRS_CAP_SHOWEXIFKEYWORDS = IDRS_CAPZERO + 10;
  IDRS_CAP_SHOWEXIFRATING = IDRS_CAPZERO + 11;
  IDRS_CAP_SHOWKEYWORDS = IDRS_CAPZERO + 12;
  IDRS_CAP_SHOWRATING = IDRS_CAPZERO + 13;
  IDRS_CAP_SHOWFILENAMEWITHOUT = IDRS_CAPZERO + 14;
  IDRS_CAP_SHOWFILEPATH = IDRS_CAPZERO + 15;
  IDRS_CAP_SHOWFILEDIMSSIZE = IDRS_CAPZERO + 16;
  IDRS_CAP_SHOWFILECREATEDATE = IDRS_CAPZERO + 17;
  IDRS_CAP_SHOWFILECREATEDATETIME = IDRS_CAPZERO + 18;
  IDRS_CAP_SHOWFILEEDITDATE = IDRS_CAPZERO + 19;
  IDRS_CAP_SHOWFILEEDITDATETIME = IDRS_CAPZERO + 20;
  IDRS_CAP_SHOWFILETYPE = IDRS_CAPZERO + 21;
  IDRS_CAP_SHOWTOPTITLE = IDRS_CAPZERO + 22;
  IDRS_CAP_SHOWBOTTOMTITLE = IDRS_CAPZERO + 23;
  IDRS_CAP_SHOWGENERAL = IDRS_CAPZERO + 24;
  IDRS_CAP_SHOWOTHER1 = IDRS_CAPZERO + 25;
  IDRS_CAP_SHOWOTHER2 = IDRS_CAPZERO + 26;
  IDRS_CAP_SHOWOTHER3 = IDRS_CAPZERO + 27;
  IDRS_CAP_SHOWOTHER4 = IDRS_CAPZERO + 28;

  IDRS_IPTCTAGZERO = 6000;
  IDRS_IPTCTAG_PS_Title = IDRS_IPTCTAGZERO + 1;
  IDRS_IPTCTAG_PS_Caption = IDRS_IPTCTAGZERO + 2;
  IDRS_IPTCTAG_PS_Keywords = IDRS_IPTCTAGZERO + 3;
  IDRS_IPTCTAG_PS_Instructions = IDRS_IPTCTAGZERO + 4;
  IDRS_IPTCTAG_PS_Date_Created = IDRS_IPTCTAGZERO + 5;
  IDRS_IPTCTAG_PS_Time_Created = IDRS_IPTCTAGZERO + 6;
  IDRS_IPTCTAG_PS_ByLine1 = IDRS_IPTCTAGZERO + 7;
  IDRS_IPTCTAG_PS_ByLine2 = IDRS_IPTCTAGZERO + 8;
  IDRS_IPTCTAG_PS_City = IDRS_IPTCTAGZERO + 9;
  IDRS_IPTCTAG_PS_State = IDRS_IPTCTAGZERO + 10;
  IDRS_IPTCTAG_PS_Country_Code = IDRS_IPTCTAGZERO + 11;
  IDRS_IPTCTAG_PS_Country_Name = IDRS_IPTCTAGZERO + 12;
  IDRS_IPTCTAG_PS_TransmissionRef = IDRS_IPTCTAGZERO + 13;
  IDRS_IPTCTAG_PS_Credit = IDRS_IPTCTAGZERO + 14;
  IDRS_IPTCTAG_PS_Editor = IDRS_IPTCTAGZERO + 15;
  IDRS_IPTCTAG_PS_EditStatus = IDRS_IPTCTAGZERO + 16;
  IDRS_IPTCTAG_PS_Urgency = IDRS_IPTCTAGZERO + 17;
  IDRS_IPTCTAG_PS_Category = IDRS_IPTCTAGZERO + 18;
  IDRS_IPTCTAG_PS_SupplCategory = IDRS_IPTCTAGZERO + 19;
  IDRS_IPTCTAG_PS_FixtureID = IDRS_IPTCTAGZERO + 20;
  IDRS_IPTCTAG_PS_ReleaseDate = IDRS_IPTCTAGZERO + 21;
  IDRS_IPTCTAG_PS_ReleaseTime = IDRS_IPTCTAGZERO + 22;
  IDRS_IPTCTAG_PS_ReferenceService = IDRS_IPTCTAGZERO + 23;
  IDRS_IPTCTAG_PS_ReferenceDate = IDRS_IPTCTAGZERO + 24;
  IDRS_IPTCTAG_PS_ReferenceNumber = IDRS_IPTCTAGZERO + 25;
  IDRS_IPTCTAG_PS_OrigProgram = IDRS_IPTCTAGZERO + 26;
  IDRS_IPTCTAG_PS_ProgVersion = IDRS_IPTCTAGZERO + 27;
  IDRS_IPTCTAG_PS_ObjectCycle = IDRS_IPTCTAGZERO + 28;
  IDRS_IPTCTAG_PS_ImageType = IDRS_IPTCTAGZERO + 29;
  IDRS_IPTCTAG_PS_CopyrightNotice = IDRS_IPTCTAGZERO + 30;

  IDRS_XMPZERO = 7000;
  IDRS_XMP_Aux_ApproximateFocusDistance = IDRS_XMPZERO + 1;
  IDRS_XMP_Aux_Firmware = IDRS_XMPZERO + 2;
  IDRS_XMP_Aux_FlashCompensation = IDRS_XMPZERO + 3;
  IDRS_XMP_Aux_ImageNumber = IDRS_XMPZERO + 4;
  IDRS_XMP_Aux_Lens = IDRS_XMPZERO + 5;
  IDRS_XMP_Aux_LensID = IDRS_XMPZERO + 6;
  IDRS_XMP_Aux_LensInfo = IDRS_XMPZERO + 7;
  IDRS_XMP_Aux_LensSerialNumber = IDRS_XMPZERO + 8;
  IDRS_XMP_Aux_OwnerName = IDRS_XMPZERO + 9;
  IDRS_XMP_Aux_SerialNumber = IDRS_XMPZERO + 10;
  IDRS_XMP_CC_AttributionName = IDRS_XMPZERO + 11;
  IDRS_XMP_CC_AttributionURL = IDRS_XMPZERO + 12;
  IDRS_XMP_CC_DeprecatedOn = IDRS_XMPZERO + 13;
  IDRS_XMP_CC_Jurisdiction = IDRS_XMPZERO + 14;
  IDRS_XMP_CC_LegalCode = IDRS_XMPZERO + 15;
  IDRS_XMP_CC_License = IDRS_XMPZERO + 16;
  IDRS_XMP_CC_MorePermissions = IDRS_XMPZERO + 17;
  IDRS_XMP_CC_Permits = IDRS_XMPZERO + 18;
  IDRS_XMP_CC_Prohibits = IDRS_XMPZERO + 19;
  IDRS_XMP_CC_Requires = IDRS_XMPZERO + 20;
  IDRS_XMP_CC_UseGuidelines = IDRS_XMPZERO + 21;
  IDRS_XMP_DC_Contributor = IDRS_XMPZERO + 22;
  IDRS_XMP_DC_Coverage = IDRS_XMPZERO + 23;
  IDRS_XMP_DC_Creator = IDRS_XMPZERO + 24;
  IDRS_XMP_DC_Date = IDRS_XMPZERO + 25;
  IDRS_XMP_DC_Description = IDRS_XMPZERO + 26;
  IDRS_XMP_DC_Format = IDRS_XMPZERO + 27;
  IDRS_XMP_DC_Identifier = IDRS_XMPZERO + 28;
  IDRS_XMP_DC_Language = IDRS_XMPZERO + 29;
  IDRS_XMP_DC_Publisher = IDRS_XMPZERO + 30;
  IDRS_XMP_DC_Relation = IDRS_XMPZERO + 31;
  IDRS_XMP_DC_Rights = IDRS_XMPZERO + 32;
  IDRS_XMP_DC_Source = IDRS_XMPZERO + 33;
  IDRS_XMP_DC_Subject = IDRS_XMPZERO + 34;
  IDRS_XMP_DC_Title = IDRS_XMPZERO + 35;
  IDRS_XMP_DC_Type = IDRS_XMPZERO + 36;
  IDRS_XMP_Photoshop_AuthorsPosition = IDRS_XMPZERO + 37;
  IDRS_XMP_Photoshop_CaptionWriter = IDRS_XMPZERO + 38;
  IDRS_XMP_Photoshop_Category = IDRS_XMPZERO + 39;
  IDRS_XMP_Photoshop_City = IDRS_XMPZERO + 40;
  IDRS_XMP_Photoshop_ColorMode = IDRS_XMPZERO + 41;
  IDRS_XMP_Photoshop_Country = IDRS_XMPZERO + 42;
  IDRS_XMP_Photoshop_Credit = IDRS_XMPZERO + 43;
  IDRS_XMP_Photoshop_DateCreated = IDRS_XMPZERO + 44;
  IDRS_XMP_Photoshop_DocumentAncestorID = IDRS_XMPZERO + 45;
  IDRS_XMP_Photoshop_Headline = IDRS_XMPZERO + 46;
  IDRS_XMP_Photoshop_History = IDRS_XMPZERO + 47;
  IDRS_XMP_Photoshop_ICCProfileName = IDRS_XMPZERO + 48;
  IDRS_XMP_Photoshop_Instructions = IDRS_XMPZERO + 49;
  IDRS_XMP_Photoshop_Source = IDRS_XMPZERO + 50;
  IDRS_XMP_Photoshop_State = IDRS_XMPZERO + 51;
  IDRS_XMP_Photoshop_SupplementalCategories = IDRS_XMPZERO + 52;
  IDRS_XMP_Photoshop_TextLayerName = IDRS_XMPZERO + 53;
  IDRS_XMP_Photoshop_TextLayerText = IDRS_XMPZERO + 54;
  IDRS_XMP_Photoshop_TransmissionReference = IDRS_XMPZERO + 55;
  IDRS_XMP_Photoshop_Urgency = IDRS_XMPZERO + 56;
  IDRS_XMP_Advisory = IDRS_XMPZERO + 57;
  IDRS_XMP_Author = IDRS_XMPZERO + 58;
  IDRS_XMP_BaseURL = IDRS_XMPZERO + 59;
  IDRS_XMP_CreateDate = IDRS_XMPZERO + 60;
  IDRS_XMP_CreatorTool = IDRS_XMPZERO + 61;
  IDRS_XMP_Description = IDRS_XMPZERO + 62;
  IDRS_XMP_Format = IDRS_XMPZERO + 63;
  IDRS_XMP_Identifier = IDRS_XMPZERO + 64;
  IDRS_XMP_Keywords = IDRS_XMPZERO + 65;
  IDRS_XMP_Label = IDRS_XMPZERO + 66;
  IDRS_XMP_MetadataDate = IDRS_XMPZERO + 67;
  IDRS_XMP_ModifyDate = IDRS_XMPZERO + 68;
  IDRS_XMP_Nickname = IDRS_XMPZERO + 69;
  IDRS_XMP_Rating = IDRS_XMPZERO + 70;
  IDRS_XMP_Title = IDRS_XMPZERO + 71;

  IDRS_EXIFZERO = 8000;
  IDRS_EXIF_UserComment = IDRS_EXIFZERO + 1;
  IDRS_EXIF_ImageDescription = IDRS_EXIFZERO + 2;
  IDRS_EXIF_CameraMake = IDRS_EXIFZERO + 3;
  IDRS_EXIF_CameraModel = IDRS_EXIFZERO + 4;
  IDRS_EXIF_XResolution = IDRS_EXIFZERO + 5;
  IDRS_EXIF_YResolution = IDRS_EXIFZERO + 6;
  IDRS_EXIF_DateTime = IDRS_EXIFZERO + 7;
  IDRS_EXIF_DateTimeOriginal = IDRS_EXIFZERO + 8;
  IDRS_EXIF_DateTimeDigitized = IDRS_EXIFZERO + 9;
  IDRS_EXIF_Copyright = IDRS_EXIFZERO + 10;
  IDRS_EXIF_Orientation = IDRS_EXIFZERO + 11;
  IDRS_EXIF_ExposureTime = IDRS_EXIFZERO + 12;
  IDRS_EXIF_FNumber = IDRS_EXIFZERO + 13;
  IDRS_EXIF_ExposureProgram = IDRS_EXIFZERO + 14;
  IDRS_EXIF_ISOSpeedRatings = IDRS_EXIFZERO + 15;
  IDRS_EXIF_ShutterSpeedValue = IDRS_EXIFZERO + 16;
  IDRS_EXIF_ApertureValue = IDRS_EXIFZERO + 17;
  IDRS_EXIF_BrightnessValue = IDRS_EXIFZERO + 18;
  IDRS_EXIF_ExposureBiasValue = IDRS_EXIFZERO + 19;
  IDRS_EXIF_MaxApertureValue = IDRS_EXIFZERO + 20;
  IDRS_EXIF_SubjectDistance = IDRS_EXIFZERO + 21;
  IDRS_EXIF_MeteringMode = IDRS_EXIFZERO + 22;
  IDRS_EXIF_LightSource = IDRS_EXIFZERO + 23;
  IDRS_EXIF_Flash = IDRS_EXIFZERO + 24;
  IDRS_EXIF_FocalLength = IDRS_EXIFZERO + 25;
  IDRS_EXIF_FlashPixVersion = IDRS_EXIFZERO + 26;
  IDRS_EXIF_ColorSpace = IDRS_EXIFZERO + 27;
  IDRS_EXIF_ExifImageWidth = IDRS_EXIFZERO + 28;
  IDRS_EXIF_ExifImageHeight = IDRS_EXIFZERO + 29;
  IDRS_EXIF_RelatedSoundFile = IDRS_EXIFZERO + 30;
  IDRS_EXIF_FocalPlaneXResolution = IDRS_EXIFZERO + 31;
  IDRS_EXIF_FocalPlaneYResolution = IDRS_EXIFZERO + 32;
  IDRS_EXIF_ExposureIndex = IDRS_EXIFZERO + 33;
  IDRS_EXIF_SensingMethod = IDRS_EXIFZERO + 34;
  IDRS_EXIF_FileSource = IDRS_EXIFZERO + 35;
  IDRS_EXIF_SceneType = IDRS_EXIFZERO + 36;
  IDRS_EXIF_YCbCrPositioning = IDRS_EXIFZERO + 37;
  IDRS_EXIF_ExposureMode = IDRS_EXIFZERO + 38;
  IDRS_EXIF_WhiteBalance = IDRS_EXIFZERO + 39;
  IDRS_EXIF_DigitalZoomRatio = IDRS_EXIFZERO + 40;
  IDRS_EXIF_FocalLengthIn35mmFilm = IDRS_EXIFZERO + 41;
  IDRS_EXIF_SceneCaptureType = IDRS_EXIFZERO + 42;
  IDRS_EXIF_GainControl = IDRS_EXIFZERO + 43;
  IDRS_EXIF_Contrast = IDRS_EXIFZERO + 44;
  IDRS_EXIF_Saturation = IDRS_EXIFZERO + 45;
  IDRS_EXIF_Sharpness = IDRS_EXIFZERO + 46;
  IDRS_EXIF_SubjectDistanceRange = IDRS_EXIFZERO + 47;
  IDRS_EXIF_GPSLatitude = IDRS_EXIFZERO + 48;
  IDRS_EXIF_GPSLongitude = IDRS_EXIFZERO + 49;
  IDRS_EXIF_GPSAltitude = IDRS_EXIFZERO + 50;
  IDRS_EXIF_GPSImageDirection = IDRS_EXIFZERO + 51;
  IDRS_EXIF_GPSTrack = IDRS_EXIFZERO + 52;
  IDRS_EXIF_GPSSpeed = IDRS_EXIFZERO + 53;
  IDRS_EXIF_GPSDateAndTime = IDRS_EXIFZERO + 54;
  IDRS_EXIF_GPSSatellites = IDRS_EXIFZERO + 55;
  IDRS_EXIF_GPSVersionID = IDRS_EXIFZERO + 56;
  IDRS_EXIF_Artist = IDRS_EXIFZERO + 57;
  IDRS_EXIF_XPTitle = IDRS_EXIFZERO + 58;
  IDRS_EXIF_XPComment = IDRS_EXIFZERO + 59;
  IDRS_EXIF_XPAuthor = IDRS_EXIFZERO + 60;
  IDRS_EXIF_XPKeywords = IDRS_EXIFZERO + 61;
  IDRS_EXIF_XPSubject = IDRS_EXIFZERO + 62;
  IDRS_EXIF_XPRating = IDRS_EXIFZERO + 63;
  IDRS_EXIF_InteropVersion = IDRS_EXIFZERO + 64;
  IDRS_EXIF_CameraOwnerName = IDRS_EXIFZERO + 65;
  IDRS_EXIF_BodySerialNumber = IDRS_EXIFZERO + 66;
  IDRS_EXIF_LensMake = IDRS_EXIFZERO + 67;
  IDRS_EXIF_LensModel = IDRS_EXIFZERO + 68;
  IDRS_EXIF_LensSerialNumber = IDRS_EXIFZERO + 69;
  IDRS_EXIF_Gamma = IDRS_EXIFZERO + 70;
  IDRS_EXIF_SubjectArea = IDRS_EXIFZERO + 71;
  IDRS_EXIF_SubjectLocation = IDRS_EXIFZERO + 72;




  type

  TTBTranslateMemory = class
  public

    FRS_TBSORT_NameA: string; // 'Name ->';
    FRS_TBSORT_NameD: string; // 'Name <-';
    FRS_TBSORT_DateA: string; // 'Date ->';
    FRS_TBSORT_DateD: string; // 'Date <-';
    FRS_TBSORT_ExifDateA: string; // 'Exif Date ->';
    FRS_TBSORT_ExifDateD: string; // 'Exif Date <-';
    FRS_TBSORT_SizeA: string; //
    FRS_TBSORT_SizeD: string; //
    FRS_TBSORT_FolderA: string; //
    FRS_TBSORT_FolderD: string; //
    FRS_TBSORT_FileTypeA: string; //
    FRS_TBSORT_FileTypeD: string; //
    FRS_TBSORT_NameNaturalA: string; //
    FRS_TBSORT_NameNaturalD: string; //
    FRS_TBSORT_FolderNaturalA: string; //
    FRS_TBSORT_FolderNaturalD: string; //

    FRS_METAHLP_Index : string; // 'Nr.';
    FRS_METAHLP_Field : string; // 'Field';
    FRS_METAHLP_ErrorParsingWrongGridFormat : string; // 'Parsing Error: Wrong Grid Format';

    FRS_METAPN_DISPLAYMODE_NONEMPTY : string; // 'Display Non-Empty';
    FRS_METAPN_DISPLAYMODE_All : string; // 'Display All';
    FRS_METAPN_DISPLAYMODE_GROUPED : string; // 'Display Grouped by Core';
    FRS_METAPN_PENDINGCHANGES_SINGLE : string; // 'Infos for the current file were modified. Save the changes?';
    FRS_METAPN_PENDINGCHANGES_MULTI : string; // 'Infos for multiple files were modified. Save the changes?';
    FRS_METAPN_TABCOMMON : string;

    FRS_SH_OP_DELETINGFILES : string; // 'Deleting Files..';
    FRS_SH_OP_RECYCLINGFILES : string; // 'Recycling Files..';
    FRS_SH_OP_MOVINGFILES : string; // 'Moving Files..';
    FRS_SH_OP_COPYINGFILES : string; // 'Copying Files..';
    FRS_SH_OP_SAVINGFILES : string; // 'Saving Files..';
    FRS_SH_OP_CORRECTINGORIENTATION : string; // 'Correcting Files Orientation (EXIF)..';
    FRS_SH_OP_ROTATINGFILES : string; // 'Rotating Files..';
    FRS_SH_OP_WARNING_RECYCLE_NOTALLOWED_WPD : string; // 'Warning! Recycling not allowed for %s' + ' files because they are on Portable Devices.' + ' Instead do you want to delete them? (This cannot be undone!)';
    FRS_SH_OP_WARNING_RECYCLE_NOTALLOWED_WIA : string; // 'Warning! Recycling not allowed for %s' + ' files because they are retrieved on a WIA connection.' + ' Instead do you want to delete them? (This cannot be undone!)';
    FRS_SH_OP_WARNING_INTERNETFILE_CANNOTBEMOVED : string; // 'There are internet files, for which only a copy is possible.' + 'Do you want to transfer them anyway?';
    FRS_INFOFORM_FDate : string; // 'Date: ';
    FRS_INFOFORM_FSize : string; // 'Image Size: ';
    FRS_INFOFORM_HINT_ADDEXIFINFO : string; // 'Add Exif Info';
    FRS_INFOFORM_HINT_ADDIPTCINFO : string; // 'Add IPTC Info';
    FRS_INFOFORM_ERROR_CANNOTWRITEMETA : string; // 'Cannot write metadata to this file';
    FRS_INFOFORM_BTNSAVE : string; // 'Save';
    FRS_INFOFORM_BTNSAVERENAME : string; // 'Save/Rename';
    FRS_INFOFORM_BTNRENAME : string; // 'Rename';
    FRS_INFOFORM_BTNADDEXIF : string; // 'Add Exif';
    FRS_INFOFORM_BTNADDIPTC : string; // 'Add Iptc';

    FRS_CAP_SHOWFILENAME : string; // 'Name';
    FRS_CAP_SHOWFILEDATE : string; // 'Date';
    FRS_CAP_SHOWFILESIZE : string; // 'Size';
    FRS_CAP_SHOWFILEDIMS : string; // 'Dimensions';
    FRS_CAP_SHOWEXIFDATETIME : string; // 'Exif Date-Time';
    FRS_CAP_SHOWEXIFAUTHOR : string; // 'Exif Author';
    FRS_CAP_SHOWEXIFTITLE : string; // 'Exif Title';
    FRS_CAP_SHOWEXIFSUBJECT : string; // 'Exif Subject';
    FRS_CAP_SHOWEXIFCOMMENT : string; // 'Exif Comment';
    FRS_CAP_SHOWEXIFKEYWORDS : string; // 'Exif Keywords';
    FRS_CAP_SHOWEXIFRATING : string; // 'Exif Rating';
    FRS_CAP_SHOWKEYWORDS : string; // 'Keywords';
    FRS_CAP_SHOWRATING : string; // 'Rating';
    FRS_CAP_SHOWFILENAMEWITHOUT : string; // 'Name';
    FRS_CAP_SHOWFILEPATH : string; // 'Path';
    FRS_CAP_SHOWFILEDIMSSIZE : string; // 'Dimensions and Size';
    FRS_CAP_SHOWFILECREATEDATE : string; // 'Create Date';
    FRS_CAP_SHOWFILECREATEDATETIME : string; // 'Create Date-Time';
    FRS_CAP_SHOWFILEEDITDATE : string; // 'Edit Date';
    FRS_CAP_SHOWFILEEDITDATETIME : string; // 'Edit Date-Time';
    FRS_CAP_SHOWFILETYPE : string; // 'File Type';
    FRS_CAP_SHOWTOPTITLE : string; // 'Top Title';
    FRS_CAP_SHOWBOTTOMTITLE : string; // 'Bottom Title';
    FRS_CAP_SHOWGENERAL : string; // 'Info';
    FRS_CAP_SHOWOTHER1 : string;
    FRS_CAP_SHOWOTHER2 : string;
    FRS_CAP_SHOWOTHER3 : string;
    FRS_CAP_SHOWOTHER4 : string;

    FRS_IPTCTAG_PS_Title : string; // 'Title'; // Object name
    FRS_IPTCTAG_PS_Caption : string; // 'Caption'; // Caption/Abstract
    FRS_IPTCTAG_PS_Keywords : string; // 'Keywords';
    FRS_IPTCTAG_PS_Instructions : string; // 'Special Instructions';

    FRS_IPTCTAG_PS_Date_Created : string; // 'Date Created (YYYYMMDD)';
    FRS_IPTCTAG_PS_Time_Created : string; // 'Time Created (HHMMSS±HHMM)';
    FRS_IPTCTAG_PS_ByLine1 : string; // 'By-line 1';
    FRS_IPTCTAG_PS_ByLine2 : string; // 'By-line 2';
    FRS_IPTCTAG_PS_City : string; // 'City';
    FRS_IPTCTAG_PS_State : string; // 'State/Province';
    FRS_IPTCTAG_PS_Country_Code : string; // 'Country/ Location Code';
    FRS_IPTCTAG_PS_Country_Name : string; // 'Country/ Location Name';
    FRS_IPTCTAG_PS_TransmissionRef : string; // 'Original Transmission Reference';
    FRS_IPTCTAG_PS_Credit : string; // 'Credit';
    FRS_IPTCTAG_PS_Editor : string; // 'Editor';
    FRS_IPTCTAG_PS_EditStatus : string; // 'Edit status';
    FRS_IPTCTAG_PS_Urgency : string; // 'Urgency';
    FRS_IPTCTAG_PS_Category : string; // 'Category';
    FRS_IPTCTAG_PS_SupplCategory : string; // 'Supplemental Category';
    FRS_IPTCTAG_PS_FixtureID : string; // 'Fixture Identifier';
    FRS_IPTCTAG_PS_ReleaseDate : string; // 'Release Date (YYYYMMDD)';
    FRS_IPTCTAG_PS_ReleaseTime : string; // 'Release Time (HHMMSS±HHMM)';
    FRS_IPTCTAG_PS_ReferenceService : string; // 'Reference Service';
    FRS_IPTCTAG_PS_ReferenceDate : string; // 'Reference Date (YYYYMMDD)';
    FRS_IPTCTAG_PS_ReferenceNumber : string; // 'Reference Number';
    FRS_IPTCTAG_PS_OrigProgram : string; // 'Originating Program';
    FRS_IPTCTAG_PS_ProgVersion : string; // 'Program Version';
    FRS_IPTCTAG_PS_ObjectCycle : string; // 'Object Cycle (a=AM, b=PM, c=both)';
    FRS_IPTCTAG_PS_ImageType : string; // 'Image Type';
    FRS_IPTCTAG_PS_CopyrightNotice : string; // 'Copyright Notice';

    FRS_XMP_Aux_ApproximateFocusDistance : string; // 'Focus Distance';
    FRS_XMP_Aux_Firmware : string; // 'Firmware';
    FRS_XMP_Aux_FlashCompensation : string; // 'Flash Compensation';
    FRS_XMP_Aux_ImageNumber : string; // 'Image Number';
    FRS_XMP_Aux_Lens : string; // 'Lens';
    FRS_XMP_Aux_LensID : string; // 'Lens ID';
    FRS_XMP_Aux_LensInfo : string; // 'Lens Info';
    FRS_XMP_Aux_LensSerialNumber : string; // 'Lens Serial Number';
    FRS_XMP_Aux_OwnerName : string; // 'Owner Name';
    FRS_XMP_Aux_SerialNumber : string; // 'Serial Number';
    FRS_XMP_CC_AttributionName : string; // 'Attribution Name';
    FRS_XMP_CC_AttributionURL : string; // 'Attribution URL';
    FRS_XMP_CC_DeprecatedOn : string; // 'Deprecated On';
    FRS_XMP_CC_Jurisdiction : string; // 'Jurisdiction';
    FRS_XMP_CC_LegalCode : string; // 'Legal Code';
    FRS_XMP_CC_License : string; // 'License';
    FRS_XMP_CC_MorePermissions : string; // 'More Permissions';
    FRS_XMP_CC_Permits : string; // 'Permits';
    FRS_XMP_CC_Prohibits : string; // 'Prohibits';
    FRS_XMP_CC_Requires : string; // 'Requires';
    FRS_XMP_CC_UseGuidelines : string; // 'Use Guidelines';

    FRS_XMP_DC_Contributor : string; // 'Contributor';
    FRS_XMP_DC_Coverage : string; // 'Coverage';
    FRS_XMP_DC_Creator : string; // 'Creator';
    FRS_XMP_DC_Date : string; // 'Date';
    FRS_XMP_DC_Description : string; // 'Description';
    FRS_XMP_DC_Format : string; // 'Format';
    FRS_XMP_DC_Identifier : string; // 'Identifier';
    FRS_XMP_DC_Language : string; // 'Language';
    FRS_XMP_DC_Publisher : string; // 'Publisher';
    FRS_XMP_DC_Relation : string; // 'Relation';
    FRS_XMP_DC_Rights : string; // 'Rights';
    FRS_XMP_DC_Source : string; // 'Source';
    FRS_XMP_DC_Subject : string; // 'Subject';
    FRS_XMP_DC_Title : string; // 'Title';
    FRS_XMP_DC_Type : string; // 'Type';

    FRS_XMP_Photoshop_AuthorsPosition : string; // 'Authors Position';
    FRS_XMP_Photoshop_CaptionWriter : string; // 'Caption Writer';
    FRS_XMP_Photoshop_Category : string; // 'Category';
    FRS_XMP_Photoshop_City : string; // 'City';
    FRS_XMP_Photoshop_ColorMode : string; // 'Color Mode';
    FRS_XMP_Photoshop_Country : string; // 'Country';
    FRS_XMP_Photoshop_Credit : string; // 'Credit';
    FRS_XMP_Photoshop_DateCreated : string; // 'Date Created';
    FRS_XMP_Photoshop_DocumentAncestorID : string; // 'Document Ancestor ID';
    FRS_XMP_Photoshop_Headline : string; // 'Headline';
    FRS_XMP_Photoshop_History : string; // 'History';
    FRS_XMP_Photoshop_ICCProfileName : string; // 'ICC Profile Name';
    FRS_XMP_Photoshop_Instructions : string; // 'Instructions';
    FRS_XMP_Photoshop_Source : string; // 'Source';
    FRS_XMP_Photoshop_State : string; // 'State';
    FRS_XMP_Photoshop_SupplementalCategories : string; // 'Supplemental Categories';
    FRS_XMP_Photoshop_TextLayerName : string; // 'Text-Layer Name';
    FRS_XMP_Photoshop_TextLayerText : string; // 'Text-Layer Text';
    FRS_XMP_Photoshop_TransmissionReference : string; // 'Transmission Reference';
    FRS_XMP_Photoshop_Urgency : string; // 'Urgency';

    FRS_XMP_Advisory : string; // 'Advisory';
    FRS_XMP_Author : string; // 'Author';
    FRS_XMP_BaseURL : string; // 'BaseURL';
    FRS_XMP_CreateDate : string; // 'Create Date';
    FRS_XMP_CreatorTool : string; // 'Creator Tool';
    FRS_XMP_Description : string; // 'Description';
    FRS_XMP_Format : string; // 'Format';
    FRS_XMP_Identifier : string; // 'Identifier';
    FRS_XMP_Keywords : string; // 'Keywords';
    FRS_XMP_Label : string; // 'Label';
    FRS_XMP_MetadataDate : string; // 'Metadata Date';
    FRS_XMP_ModifyDate : string; // 'Modify Date';
    FRS_XMP_Nickname : string; // 'Nickname';
    FRS_XMP_Rating : string; // 'Rating';
    FRS_XMP_Title : string; // 'Title';

    FRS_EXIF_UserComment : string; // 'User Comment';
    FRS_EXIF_ImageDescription : string; // 'Image Description';
    FRS_EXIF_CameraMake : string; // 'Camera Make';
    FRS_EXIF_CameraModel : string; // 'Camera Model';
    FRS_EXIF_XResolution : string; // 'X Resolution';
    FRS_EXIF_YResolution : string; // 'Y Resolution';
    FRS_EXIF_DateTime : string; // 'Date-Time';
    FRS_EXIF_DateTimeOriginal : string; // 'Date-Time Original';
    FRS_EXIF_DateTimeDigitized : string; // 'Date-Time Digitized';
    FRS_EXIF_Copyright : string; // 'Copyright';
    FRS_EXIF_Orientation : string; // 'Orientation';
    FRS_EXIF_ExposureTime : string; // 'Exposure Time';
    FRS_EXIF_FNumber : string; // 'FNumber';
    FRS_EXIF_ExposureProgram : string; // 'Exposure Program';
    FRS_EXIF_ISOSpeedRatings : string; // 'ISO Speed Ratings';
    FRS_EXIF_ShutterSpeedValue : string; // 'Shutter Speed Value';
    FRS_EXIF_ApertureValue : string; // 'Aperture';
    FRS_EXIF_BrightnessValue : string; // 'Brightness';
    FRS_EXIF_ExposureBiasValue : string; // 'ExposureBias';
    FRS_EXIF_MaxApertureValue : string; // 'Max Aperture';
    FRS_EXIF_SubjectDistance : string; // 'Subject Distance';
    FRS_EXIF_MeteringMode : string; // 'Metering Mode';
    FRS_EXIF_LightSource : string; // 'Light Source';
    FRS_EXIF_Flash : string; // 'Flash';
    FRS_EXIF_FocalLength : string; // 'Focal Length';
    FRS_EXIF_FlashPixVersion : string; // 'FlashPix V.';
    FRS_EXIF_ColorSpace : string; // 'Color Space';
    FRS_EXIF_ExifImageWidth : string; // 'Image Width';
    FRS_EXIF_ExifImageHeight : string; // 'Image Height';
    FRS_EXIF_RelatedSoundFile : string; // 'Related Sound File';
    FRS_EXIF_FocalPlaneXResolution : string; // 'Focal Plane XRes';
    FRS_EXIF_FocalPlaneYResolution : string; // 'Focal Plane YRes';
    FRS_EXIF_ExposureIndex : string; // 'Exposure Index';
    FRS_EXIF_SensingMethod : string; // 'Sensing Method';
    FRS_EXIF_FileSource : string; // 'File Source';
    FRS_EXIF_SceneType : string; // 'Scene Type';
    FRS_EXIF_YCbCrPositioning : string; // 'YCbCr Positioning';
    FRS_EXIF_ExposureMode : string; // 'Exposure Mode';
    FRS_EXIF_WhiteBalance : string; // 'White Balance';
    FRS_EXIF_DigitalZoomRatio : string; // 'Digital-Zoom Ratio';
    FRS_EXIF_FocalLengthIn35mmFilm : string; // 'Focal Length 35mm eq.';
    FRS_EXIF_SceneCaptureType : string; // 'Scene Capture Type';
    FRS_EXIF_GainControl : string; // 'Gain Control';
    FRS_EXIF_Contrast : string; // 'Contrast';
    FRS_EXIF_Saturation : string; // 'Saturation';
    FRS_EXIF_Sharpness : string; // 'Sharpness';
    FRS_EXIF_SubjectDistanceRange : string; // 'Subject Distance Range';
    FRS_EXIF_GPSLatitude : string; // 'GPS Latitude';
    FRS_EXIF_GPSLongitude : string; // 'GPS Longitude';
    FRS_EXIF_GPSAltitude : string; // 'GPS Altitude';
    FRS_EXIF_GPSImageDirection : string; // 'GPS Image Direction';
    FRS_EXIF_GPSTrack : string; // 'GPS Track';
    FRS_EXIF_GPSSpeed : string; // 'GPS Speed';
    FRS_EXIF_GPSDateAndTime : string; // 'GPS Date And Time';
    FRS_EXIF_GPSSatellites : string; // 'GPS Satellites';
    FRS_EXIF_GPSVersionID : string; // 'GPS VersionID';
    FRS_EXIF_Artist : string; // 'Artist';
    FRS_EXIF_XPTitle : string; // 'Title (Windows)';
    FRS_EXIF_XPComment : string; // 'Comment (Windows)';
    FRS_EXIF_XPAuthor : string; // 'Author (Windows)';
    FRS_EXIF_XPKeywords : string; // 'Keywords (Windows)';
    FRS_EXIF_XPSubject : string; // 'Subject (Windows)';
    FRS_EXIF_XPRating : string; // 'Rating (Windows)';
    FRS_EXIF_InteropVersion : string; // 'Interop Version';
    FRS_EXIF_CameraOwnerName : string; // 'Camera Owner Name';
    FRS_EXIF_BodySerialNumber : string; // 'Body Serial Number';
    FRS_EXIF_LensMake : string; // 'Lens Make';
    FRS_EXIF_LensModel : string; // 'Lens Model';
    FRS_EXIF_LensSerialNumber : string; // 'Lens Serial Number';
    FRS_EXIF_Gamma : string; // 'Gamma';
    FRS_EXIF_SubjectArea : string; // 'Subject Area';
    FRS_EXIF_SubjectLocation : string; // 'Subject Location';

  end;

implementation


end.
