 (*
Part of NWSComps Bundle
v. 3
Copyright (C) Francesco Savastano. All Rights Reserved.

This software comes without any warranty either implied or expressed.
In no case shall the author be liable for any damage or unwanted behavior
 of any computer hardware and/or software.

You cannot DISTRIBUTE THIS SOURCE CODE OR ITS COMPILED .DCU IN ANY FORM.

This unit cannot be included in any commercial, shareware or freeware DELPHI
libraries or components.

email: nws@centurybyte.com
web site: www.nwscomps.com
*)
unit NWSComps_RGBCurves_Const;
{$R-}
{$Q-}
interface
  const

  G_CONST_RGBCURVES_VERSION_INT = 4000;
  G_CONST_RGBCURVES_VERSION_STR = '4.0.0';

  G_CONST_RGBCURVES_ALG_2000_1 =  'ALG_2000_1';
  G_CONST_RGBCURVES_ALG_3200_1 =  'ALG_3200_1';

 









  //----------------------------------------------------------------------------

  G_CONST_RGBCURVES_INIFILE_DATA_MARKER_OLD = 'data_';
  G_CONST_RGBCURVES_FILE_HEADER_TITLE_VALUE_OLD = 'Focus Photoeditor curves';
  G_CONST_RGBCURVES_FILE_HEADER_VERSION_VALUE_OLD = 'v.1.0';
  G_CONST_RGBCURVES_FILE_RGBPOINTS_TAG_OLD = 'RGB Points';
  G_CONST_RGBCURVES_FILE_REDPOINTS_TAG_OLD = 'RED Points';
  G_CONST_RGBCURVES_FILE_GREENPOINTS_TAG_OLD = 'GREEN Points';
  G_CONST_RGBCURVES_FILE_BLUEPOINTS_TAG_OLD = 'BLUE Points';


  //-------------------------------------------------------------------------


  G_CONST_RGBCURVES_FILE_TAG_START = '_TAG_START';
  G_CONST_RGBCURVES_FILE_TAG_END = '_TAG_END';

  G_CONST_RGBCURVES_INIFILE_DATA_MARKER = 'data_';
  G_CONST_RGBCURVES_FILE_TAG_HEADER_TITLE = 'TAG_HEADER_TITLE';
  G_CONST_RGBCURVES_FILE_TAG_HEADER_GUID = 'TAG_HEADER_GUID';
  G_CONST_RGBCURVES_FILE_TAG_HEADER_VERSION = 'TAG_HEADER_VERSION';
  G_CONST_RGBCURVES_FILE_TAG_ALGORITHM = 'TAG_ALGORITHM';


  G_CONST_RGBCURVES_FILE_TAG_INTERPLIN_MIN = 'TAG_INTERPLIN_MIN';
  G_CONST_RGBCURVES_FILE_TAG_INTERPLIN_MAX = 'TAG_INTERPLIN_MAX';
  G_CONST_RGBCURVES_FILE_TAG_DECSEP = 'TAG_DECSEP';
  G_CONST_RGBCURVES_FILE_TAG_POINTCOORDSSEP = 'TAG_POINTCOORDSSEP';
  G_CONST_RGBCURVES_FILE_TAG_PROPERTYSEP = 'TAG_PROPERTYVALUESEP';

  G_CONST_RGBCURVES_FILE_TAG_COMPLEMENTARY  = 'TAG_COMPLEMENTARY';

  G_CONST_RGBCURVES_FILE_TAG_RGBPOINTS_DATA = 'TAG_RGBPOINTS_DATA';
  G_CONST_RGBCURVES_FILE_TAG_REDPOINTS_DATA = 'TAG_REDPOINTS_DATA';
  G_CONST_RGBCURVES_FILE_TAG_GREENPOINTS_DATA = 'TAG_GREENPOINTS_DATA';
  G_CONST_RGBCURVES_FILE_TAG_BLUEPOINTS_DATA = 'TAG_BLUEPOINTS_DATA';
  G_CONST_RGBCURVES_FILE_TAG_RGBPOINTS_PROPERTIES = 'TAG_RGBPOINTS_PROPERTIES';
  G_CONST_RGBCURVES_FILE_TAG_REDPOINTS_PROPERTIES = 'TAG_REDPOINTS_PROPERTIES';
  G_CONST_RGBCURVES_FILE_TAG_GREENPOINTS_PROPERTIES = 'TAG_GREENPOINTS_PROPERTIES';
  G_CONST_RGBCURVES_FILE_TAG_BLUEPOINTS_PROPERTIES = 'TAG_BLUEPOINTS_PROPERTIES';

  G_CONST_RGBCURVES_FILE_TAG_RGBPOINTS_COUNT = 'TAG_RGBPOINTS_COUNT';
  G_CONST_RGBCURVES_FILE_TAG_REDPOINTS_COUNT = 'TAG_REDPOINTS_COUNT';
  G_CONST_RGBCURVES_FILE_TAG_GREENPOINTS_COUNT = 'TAG_GREENPOINTS_COUNT';
  G_CONST_RGBCURVES_FILE_TAG_BLUEPOINTS_COUNT = 'TAG_BLUEPOINTS_COUNT';


  G_CONST_RGBCURVES_FILE_TAG_POINTITEM_X = 'TAG_POINTITEM_';
  G_CONST_RGBCURVES_FILE_ID_PROPERTY_USECUSTOMLAYOUT = 'USECUSTOMLAYOUT';
  G_CONST_RGBCURVES_FILE_ID_PROPERTY_CUSTOM_OUTLINECOLOR = 'CUSTOM_OUTLINECOLOR';
  G_CONST_RGBCURVES_FILE_ID_PROPERTY_CUSTOM_FILLCOLOR = 'CUSTOM_FILLCOLOR';
  G_CONST_RGBCURVES_FILE_ID_PROPERTY_CUSTOM_POINTSIZE = 'CUSTOM_POINTSIZE';
  G_CONST_RGBCURVES_FILE_ID_PROPERTY_CUSTOM_LINESIZE = 'CUSTOM_LINESIZE';



  G_CONST_RGBCURVES_FILE_HEADER_TITLE_VALUE = 'Focus Photoeditor curves';
  G_CONST_RGBCURVES_FILE_HEADER_GUID_VALUE = '{5FF3C2FD-C86E-4972-A2C0-B41B9D330CDC}';
  G_CONST_RGBCURVES_FILE_POINTCOORDSSEP_VALUE = ' | ';
  G_CONST_RGBCURVES_FILE_PROPERTYSEP_VALUE = ' | ';


implementation

end.
