 (*
Part of NWSComps Bundle
v. 3
Copyright (C) Francesco Savastano. All Rights Reserved.

This software comes without any warranty either implied or expressed.
In no case shall the author be liable for any damage or unwanted behavior
 of any computer hardware and/or software.

You cannot DISTRIBUTE THIS SOURCE CODE OR ITS COMPILED .DCU IN ANY FORM.

This unit cannot be included in any commercial, shareware or freeware DELPHI
libraries or components.

email: nws@centurybyte.com
web site: www.nwscomps.com
*)
unit NWSComps_Proc_Filter_Lib_Const;
{$R-}
{$Q-}
interface
  uses NWSComps_Proc_Filter_Types;

    Const

    //------------------------------------------
    IEPROC_EX_CUSTOMFILTER = 'Custom Filter';
    IEPROC_EX_CUSTOMFILTER_ID = 0000000;
    //------------------------------------------

    //------------------------------------------
    IEPROC_EX_SMARTFLASH = 'Smart Flash';
    IEPROC_EX_SMARTFLASH_ID = 0000001;

    IEPROC_EX_SMARTFLASH_AMOUNT = 'Amount';
    IEPROC_EX_SMARTFLASH_AMOUNT_VTYPE= pt_Int;
    IEPROC_EX_SMARTFLASH_AMOUNT_MIN =0;
    IEPROC_EX_SMARTFLASH_AMOUNT_MAX =255;
    IEPROC_EX_SMARTFLASH_AMOUNT_DEFAULT =0;

    IEPROC_EX_SMARTFLASH_RADIUS = 'Radius';
    IEPROC_EX_SMARTFLASH_RADIUS_VTYPE= pt_Int;
    IEPROC_EX_SMARTFLASH_RADIUS_MIN =1;
    IEPROC_EX_SMARTFLASH_RADIUS_MAX =50;
    IEPROC_EX_SMARTFLASH_RADIUS_DEFAULT =0;
    //---------------------------------------------

    IEPROC_EX_REDUCEHIGHLIGHTS = 'Reduce Highlights';
    IEPROC_EX_REDUCEHIGHLIGHTS_ID = 0000002;

    IEPROC_EX_REDUCEHIGHLIGHTS_AMOUNT = 'Amount';
    IEPROC_EX_REDUCEHIGHLIGHTS_AMOUNT_VTYPE= pt_Int;
    IEPROC_EX_REDUCEHIGHLIGHTS_AMOUNT_MIN =0;
    IEPROC_EX_REDUCEHIGHLIGHTS_AMOUNT_MAX =255;
    IEPROC_EX_REDUCEHIGHLIGHTS_AMOUNT_DEFAULT =0;

    IEPROC_EX_REDUCEHIGHLIGHTS_RADIUS = 'Radius';
    IEPROC_EX_REDUCEHIGHLIGHTS_RADIUS_VTYPE= pt_Int;
    IEPROC_EX_REDUCEHIGHLIGHTS_RADIUS_MIN =1;
    IEPROC_EX_REDUCEHIGHLIGHTS_RADIUS_MAX = 50;
    IEPROC_EX_REDUCEHIGHLIGHTS_RADIUS_DEFAULT = 1;
    //---------------------------------------------

    IEPROC_EX_FILLBACKLIGHT = 'Fill / Back Light';
    IEPROC_EX_FILLBACKLIGHT_ID = 0000003;

    IEPROC_EX_FILLBACKLIGHT_FILLLIGHTAMOUNT = 'Fill Light Amount';
    IEPROC_EX_FILLBACKLIGHT_FILLLIGHTAMOUNT_VTYPE= pt_Int;
    IEPROC_EX_FILLBACKLIGHT_FILLLIGHTAMOUNT_MIN =0;
    IEPROC_EX_FILLBACKLIGHT_FILLLIGHTAMOUNT_MAX =255;
    IEPROC_EX_FILLBACKLIGHT_FILLLIGHTAMOUNT_DEFAULT =0;

    IEPROC_EX_FILLBACKLIGHT_BACKLIGHTAMOUNT = 'Back Light Amount';
    IEPROC_EX_FILLBACKLIGHT_BACKLIGHTAMOUNT_VTYPE= pt_Int;
    IEPROC_EX_FILLBACKLIGHT_BACKLIGHTAMOUNT_MIN =0;
    IEPROC_EX_FILLBACKLIGHT_BACKLIGHTAMOUNT_MAX =255;
    IEPROC_EX_FILLBACKLIGHT_BACKLIGHTAMOUNT_DEFAULT =0;

    IEPROC_EX_FILLBACKLIGHT_RADIUS = 'Radius';
    IEPROC_EX_FILLBACKLIGHT_RADIUS_VTYPE= pt_Int;
    IEPROC_EX_FILLBACKLIGHT_RADIUS_MIN =1;

    IEPROC_EX_FILLBACKLIGHT_RADIUS_MAX = 50;
    IEPROC_EX_FILLBACKLIGHT_RADIUS_DEFAULT = 1;
    //---------------------------------------------

      //------------------------------------------
    IEPROC_EX_SMARTCONTRAST = 'Smart Contrast';
    IEPROC_EX_SMARTCONTRAST_ID = 0000004;

    IEPROC_EX_SMARTCONTRAST_AMOUNT = 'Amount';
    IEPROC_EX_SMARTCONTRAST_AMOUNT_VTYPE= pt_Int;
    IEPROC_EX_SMARTCONTRAST_AMOUNT_MIN =0;
    IEPROC_EX_SMARTCONTRAST_AMOUNT_MAX =255;
    IEPROC_EX_SMARTCONTRAST_AMOUNT_DEFAULT =0;

    IEPROC_EX_SMARTCONTRAST_RADIUS = 'Radius';
    IEPROC_EX_SMARTCONTRAST_RADIUS_VTYPE= pt_Int;
    IEPROC_EX_SMARTCONTRAST_RADIUS_MIN =1;
    IEPROC_EX_SMARTCONTRAST_RADIUS_MAX = 50;
    IEPROC_EX_SMARTCONTRAST_RADIUS_DEFAULT =0;
    //---------------------------------------------


    //------------------------------------------
    IEPROC_EX_RGBBALANCE = 'RGB Balance';
    IEPROC_EX_RGBBALANCE_ID = 0000005;

    IEPROC_EX_RGBBALANCE_UNIFORM = 'Uniform';
    IEPROC_EX_RGBBALANCE_UNIFORM_VTYPE= pt_boolean;
    IEPROC_EX_RGBBALANCE_UNIFORM_MIN = FALSE;
    IEPROC_EX_RGBBALANCE_UNIFORM_MAX = TRUE;
    IEPROC_EX_RGBBALANCE_UNIFORM_DEFAULT = TRUE;

    IEPROC_EX_RGBBALANCE_AMOUNT_SH_RED = 'Shadows Red';
    IEPROC_EX_RGBBALANCE_AMOUNT_SH_RED_VTYPE= pt_Int;
    IEPROC_EX_RGBBALANCE_AMOUNT_SH_RED_MIN =-255;
    IEPROC_EX_RGBBALANCE_AMOUNT_SH_RED_MAX =255;
    IEPROC_EX_RGBBALANCE_AMOUNT_SH_RED_DEFAULT =0;

    IEPROC_EX_RGBBALANCE_AMOUNT_SH_GREEN = 'Shadows Green';
    IEPROC_EX_RGBBALANCE_AMOUNT_SH_GREEN_VTYPE= pt_Int;
    IEPROC_EX_RGBBALANCE_AMOUNT_SH_GREEN_MIN =-255;
    IEPROC_EX_RGBBALANCE_AMOUNT_SH_GREEN_MAX =255;
    IEPROC_EX_RGBBALANCE_AMOUNT_SH_GREEN_DEFAULT =0;

    IEPROC_EX_RGBBALANCE_AMOUNT_SH_BLUE = 'Shadows Blue';
    IEPROC_EX_RGBBALANCE_AMOUNT_SH_BLUE_VTYPE= pt_Int;
    IEPROC_EX_RGBBALANCE_AMOUNT_SH_BLUE_MIN =-255;
    IEPROC_EX_RGBBALANCE_AMOUNT_SH_BLUE_MAX =255;
    IEPROC_EX_RGBBALANCE_AMOUNT_SH_BLUE_DEFAULT =0;


    IEPROC_EX_RGBBALANCE_AMOUNT_MID_RED = 'Midtones Red';
    IEPROC_EX_RGBBALANCE_AMOUNT_MID_RED_VTYPE= pt_Int;
    IEPROC_EX_RGBBALANCE_AMOUNT_MID_RED_MIN =-255;
    IEPROC_EX_RGBBALANCE_AMOUNT_MID_RED_MAX =255;
    IEPROC_EX_RGBBALANCE_AMOUNT_MID_RED_DEFAULT =0;

    IEPROC_EX_RGBBALANCE_AMOUNT_MID_GREEN = 'Midtones Green';
    IEPROC_EX_RGBBALANCE_AMOUNT_MID_GREEN_VTYPE= pt_Int;
    IEPROC_EX_RGBBALANCE_AMOUNT_MID_GREEN_MIN =-255;
    IEPROC_EX_RGBBALANCE_AMOUNT_MID_GREEN_MAX =255;
    IEPROC_EX_RGBBALANCE_AMOUNT_MID_GREEN_DEFAULT =0;

    IEPROC_EX_RGBBALANCE_AMOUNT_MID_BLUE = 'Midtones Blue';
    IEPROC_EX_RGBBALANCE_AMOUNT_MID_BLUE_VTYPE= pt_Int;
    IEPROC_EX_RGBBALANCE_AMOUNT_MID_BLUE_MIN =-255;
    IEPROC_EX_RGBBALANCE_AMOUNT_MID_BLUE_MAX =255;
    IEPROC_EX_RGBBALANCE_AMOUNT_MID_BLUE_DEFAULT =0;



    IEPROC_EX_RGBBALANCE_AMOUNT_HI_RED = 'HighLights Red';
    IEPROC_EX_RGBBALANCE_AMOUNT_HI_RED_VTYPE= pt_Int;
    IEPROC_EX_RGBBALANCE_AMOUNT_HI_RED_MIN =-255;
    IEPROC_EX_RGBBALANCE_AMOUNT_HI_RED_MAX =255;
    IEPROC_EX_RGBBALANCE_AMOUNT_HI_RED_DEFAULT =0;

    IEPROC_EX_RGBBALANCE_AMOUNT_HI_GREEN = 'Highlights Green';
    IEPROC_EX_RGBBALANCE_AMOUNT_HI_GREEN_VTYPE= pt_Int;
    IEPROC_EX_RGBBALANCE_AMOUNT_HI_GREEN_MIN =-255;
    IEPROC_EX_RGBBALANCE_AMOUNT_HI_GREEN_MAX =255;
    IEPROC_EX_RGBBALANCE_AMOUNT_HI_GREEN_DEFAULT =0;

    IEPROC_EX_RGBBALANCE_AMOUNT_HI_BLUE = 'Highlights Blue';
    IEPROC_EX_RGBBALANCE_AMOUNT_HI_BLUE_VTYPE= pt_Int;
    IEPROC_EX_RGBBALANCE_AMOUNT_HI_BLUE_MIN =-255;
    IEPROC_EX_RGBBALANCE_AMOUNT_HI_BLUE_MAX =255;
    IEPROC_EX_RGBBALANCE_AMOUNT_HI_BLUE_DEFAULT =0;



    IEPROC_EX_RGBBALANCE_AMOUNT_ALL_RED = 'Amount Red All';
    IEPROC_EX_RGBBALANCE_AMOUNT_ALL_RED_VTYPE= pt_Int;
    IEPROC_EX_RGBBALANCE_AMOUNT_ALL_RED_MIN =-255;
    IEPROC_EX_RGBBALANCE_AMOUNT_ALL_RED_MAX =255;
    IEPROC_EX_RGBBALANCE_AMOUNT_ALL_RED_DEFAULT =0;

    IEPROC_EX_RGBBALANCE_AMOUNT_ALL_GREEN = 'Amount Green All';
    IEPROC_EX_RGBBALANCE_AMOUNT_ALL_GREEN_VTYPE= pt_Int;
    IEPROC_EX_RGBBALANCE_AMOUNT_ALL_GREEN_MIN =-255;
    IEPROC_EX_RGBBALANCE_AMOUNT_ALL_GREEN_MAX =255;
    IEPROC_EX_RGBBALANCE_AMOUNT_ALL_GREEN_DEFAULT =0;

    IEPROC_EX_RGBBALANCE_AMOUNT_ALL_BLUE = 'Amount Blue All';
    IEPROC_EX_RGBBALANCE_AMOUNT_ALL_BLUE_VTYPE= pt_Int;
    IEPROC_EX_RGBBALANCE_AMOUNT_ALL_BLUE_MIN =-255;
    IEPROC_EX_RGBBALANCE_AMOUNT_ALL_BLUE_MAX =255;
    IEPROC_EX_RGBBALANCE_AMOUNT_ALL_BLUE_DEFAULT =0;


    //------------------------------------------


    IEPROC_EX_AUTOCOLOR = 'AutoColor';
    IEPROC_EX_AUTOCOLOR_ID = 0000006;


    IEPROC_EX_AUTOCOLOR_STRENGTH = 'Strength';
    IEPROC_EX_AUTOCOLOR_STRENGTH_VTYPE= pt_Int;
    IEPROC_EX_AUTOCOLOR_STRENGTH_MIN =1;
    IEPROC_EX_AUTOCOLOR_STRENGTH_MAX =10;
    IEPROC_EX_AUTOCOLOR_STRENGTH_DEFAULT =4;

   //---------------------------------------------


   //------------------------------------------
    IEPROC_EX_COLORFILTER = 'Color Filter';
    IEPROC_EX_COLORFILTER_ID = 0000007;


    IEPROC_EX_COLORFILTER_AMOUNT = 'Amount';
    IEPROC_EX_COLORFILTER_AMOUNT_VTYPE= pt_Byte;
    IEPROC_EX_COLORFILTER_AMOUNT_MIN =0;
    IEPROC_EX_COLORFILTER_AMOUNT_MAX =255;
    IEPROC_EX_COLORFILTER_AMOUNT_DEFAULT =0;


    IEPROC_EX_COLORFILTER_COLOR = 'Color';
    IEPROC_EX_COLORFILTER_COLOR_VTYPE= pt_int;
    IEPROC_EX_COLORFILTER_COLOR_MIN =0;
    IEPROC_EX_COLORFILTER_COLOR_MAX =MaxInt;
    IEPROC_EX_COLORFILTER_COLOR_DEFAULT =0;

    IEPROC_EX_COLORFILTER_BLENDMODE = 'Blend Mode';
    IEPROC_EX_COLORFILTER_BLENDMODE_VTYPE= pt_byte;
    IEPROC_EX_COLORFILTER_BLENDMODE_MIN =0;
    IEPROC_EX_COLORFILTER_BLENDMODE_MAX =5;
    IEPROC_EX_COLORFILTER_BLENDMODE_DEFAULT =0;

   //---------------------------------------------

    IEPROC_EX_BILATERALFILTER = 'Bilateral Filter';
    IEPROC_EX_BILATERALFILTER_ID = 0000008;


    IEPROC_EX_BILATERALFILTER_SIGMA = 'Sigma';
    IEPROC_EX_BILATERALFILTER_SIGMA_VTYPE= pt_Byte;
    IEPROC_EX_BILATERALFILTER_SIGMA_MIN =1;
    IEPROC_EX_BILATERALFILTER_SIGMA_MAX =50;
    IEPROC_EX_BILATERALFILTER_SIGMA_DEFAULT =1;


    IEPROC_EX_BILATERALFILTER_SIGMA_DISTANCE = 'Sigma Distance';
    IEPROC_EX_BILATERALFILTER_SIGMA_DISTANCE_VTYPE= pt_Byte;
    IEPROC_EX_BILATERALFILTER_SIGMA_DISTANCE_MIN =5;
    IEPROC_EX_BILATERALFILTER_SIGMA_DISTANCE_MAX =20;
    IEPROC_EX_BILATERALFILTER_SIGMA_DISTANCE_DEFAULT =14;


    IEPROC_EX_BILATERALFILTER_RADIUS = 'Radius';
    IEPROC_EX_BILATERALFILTER_RADIUS_VTYPE= pt_Byte;
    IEPROC_EX_BILATERALFILTER_RADIUS_MIN =1;
    IEPROC_EX_BILATERALFILTER_RADIUS_MAX =6;
    IEPROC_EX_BILATERALFILTER_RADIUS_DEFAULT =1;

    //-----------------------------------------



    IEPROC_EX_SMOOTHFILTER = 'Smooth';
    IEPROC_EX_SMOOTHFILTER_ID = 0000009;


    IEPROC_EX_SMOOTHFILTER_AMOUNT = 'Amount';
    IEPROC_EX_SMOOTHFILTER_AMOUNT_VTYPE= pt_int;
    IEPROC_EX_SMOOTHFILTER_AMOUNT_MIN =1;
    IEPROC_EX_SMOOTHFILTER_AMOUNT_MAX =80;
    IEPROC_EX_SMOOTHFILTER_AMOUNT_DEFAULT =1;

    //---------------------------------------------

    //color:TColor; LightAmount: integer; Angle:integer; xc,yc:integer
    IEPROC_EX_LIGHTFX_ELLIPSE = 'Light Effect - Ellipse';
    IEPROC_EX_LIGHTFX_ELLIPSE_ID = 0000010;

    IEPROC_EX_LIGHTFX_ELLIPSE_COLOR = 'Color';
    IEPROC_EX_LIGHTFX_ELLIPSE_COLOR_VTYPE= pt_int;
    IEPROC_EX_LIGHTFX_ELLIPSE_COLOR_MIN =0;
    IEPROC_EX_LIGHTFX_ELLIPSE_COLOR_MAX = MaxInt;
    IEPROC_EX_LIGHTFX_ELLIPSE_COLOR_DEFAULT =16579839;

    IEPROC_EX_LIGHTFX_ELLIPSE_LIGHTAMT = 'Light Amount';
    IEPROC_EX_LIGHTFX_ELLIPSE_LIGHTAMT_VTYPE= pt_int;
    IEPROC_EX_LIGHTFX_ELLIPSE_LIGHTAMT_MIN =0;
    IEPROC_EX_LIGHTFX_ELLIPSE_LIGHTAMT_MAX = 100;
    IEPROC_EX_LIGHTFX_ELLIPSE_LIGHTAMT_DEFAULT =50;

    IEPROC_EX_LIGHTFX_ELLIPSE_ELLIPSEMINOR = 'Ellipse Minor Axis';
    IEPROC_EX_LIGHTFX_ELLIPSE_ELLIPSEMINOR_VTYPE= pt_int;
    IEPROC_EX_LIGHTFX_ELLIPSE_ELLIPSEMINOR_MIN =1;
    IEPROC_EX_LIGHTFX_ELLIPSE_ELLIPSEMINOR_MAX =10000;
    IEPROC_EX_LIGHTFX_ELLIPSE_ELLIPSEMINOR_DEFAULT =200;

    IEPROC_EX_LIGHTFX_ELLIPSE_ELLIPSEMAJOR = 'Ellipse Major Axis';
    IEPROC_EX_LIGHTFX_ELLIPSE_ELLIPSEMAJOR_VTYPE= pt_int;
    IEPROC_EX_LIGHTFX_ELLIPSE_ELLIPSEMAJOR_MIN =1;
    IEPROC_EX_LIGHTFX_ELLIPSE_ELLIPSEMAJOR_MAX =10000;
    IEPROC_EX_LIGHTFX_ELLIPSE_ELLIPSEMAJOR_DEFAULT =400;

    IEPROC_EX_LIGHTFX_ELLIPSE_ANGLE = 'Angle';
    IEPROC_EX_LIGHTFX_ELLIPSE_ANGLE_VTYPE= pt_int;
    IEPROC_EX_LIGHTFX_ELLIPSE_ANGLE_MIN =0;
    IEPROC_EX_LIGHTFX_ELLIPSE_ANGLE_MAX =360;
    IEPROC_EX_LIGHTFX_ELLIPSE_ANGLE_DEFAULT =45;

    IEPROC_EX_LIGHTFX_ELLIPSE_CENTERX = 'Center X';
    IEPROC_EX_LIGHTFX_ELLIPSE_CENTERX_VTYPE= pt_int;
    IEPROC_EX_LIGHTFX_ELLIPSE_CENTERX_MIN =0;
    IEPROC_EX_LIGHTFX_ELLIPSE_CENTERX_MAX =10000;
    IEPROC_EX_LIGHTFX_ELLIPSE_CENTERX_DEFAULT =0;

    IEPROC_EX_LIGHTFX_ELLIPSE_CENTERY = 'Center Y';
    IEPROC_EX_LIGHTFX_ELLIPSE_CENTERY_VTYPE= pt_int;
    IEPROC_EX_LIGHTFX_ELLIPSE_CENTERY_MIN =0;
    IEPROC_EX_LIGHTFX_ELLIPSE_CENTERY_MAX =10000;
    IEPROC_EX_LIGHTFX_ELLIPSE_CENTERY_DEFAULT =0;

     //---------------------------------------------

    IEPROC_EX_LIGHTFX_BEAM = 'Light Effect - Beam';
    IEPROC_EX_LIGHTFX_BEAM_ID = 0000011;

    IEPROC_EX_LIGHTFX_BEAM_COLOR = 'Color';
    IEPROC_EX_LIGHTFX_BEAM_COLOR_VTYPE= pt_int;
    IEPROC_EX_LIGHTFX_BEAM_COLOR_MIN =0;
    IEPROC_EX_LIGHTFX_BEAM_COLOR_MAX = MaxInt;
    IEPROC_EX_LIGHTFX_BEAM_COLOR_DEFAULT =16579839;

    IEPROC_EX_LIGHTFX_BEAM_LIGHTAMT = 'Light Amount';
    IEPROC_EX_LIGHTFX_BEAM_LIGHTAMT_VTYPE= pt_int;
    IEPROC_EX_LIGHTFX_BEAM_LIGHTAMT_MIN =0;
    IEPROC_EX_LIGHTFX_BEAM_LIGHTAMT_MAX = 100;
    IEPROC_EX_LIGHTFX_BEAM_LIGHTAMT_DEFAULT =50;

    IEPROC_EX_LIGHTFX_BEAM_BEAMSIZE = 'Beam Size';
    IEPROC_EX_LIGHTFX_BEAM_BEAMSIZE_VTYPE= pt_int;
    IEPROC_EX_LIGHTFX_BEAM_BEAMSIZE_MIN =1;
    IEPROC_EX_LIGHTFX_BEAM_BEAMSIZE_MAX =5000;
    IEPROC_EX_LIGHTFX_BEAM_BEAMSIZE_DEFAULT =50;

    IEPROC_EX_LIGHTFX_BEAM_ANGLE = 'Angle';
    IEPROC_EX_LIGHTFX_BEAM_ANGLE_VTYPE= pt_int;
    IEPROC_EX_LIGHTFX_BEAM_ANGLE_MIN =0;
    IEPROC_EX_LIGHTFX_BEAM_ANGLE_MAX =360;
    IEPROC_EX_LIGHTFX_BEAM_ANGLE_DEFAULT =45;

    IEPROC_EX_LIGHTFX_BEAM_CENTERX = 'Center X';
    IEPROC_EX_LIGHTFX_BEAM_CENTERX_VTYPE= pt_int;
    IEPROC_EX_LIGHTFX_BEAM_CENTERX_MIN =0;
    IEPROC_EX_LIGHTFX_BEAM_CENTERX_MAX =10000;
    IEPROC_EX_LIGHTFX_BEAM_CENTERX_DEFAULT =0;

    IEPROC_EX_LIGHTFX_BEAM_CENTERY = 'Center Y';
    IEPROC_EX_LIGHTFX_BEAM_CENTERY_VTYPE= pt_int;
    IEPROC_EX_LIGHTFX_BEAM_CENTERY_MIN =0;
    IEPROC_EX_LIGHTFX_BEAM_CENTERY_MAX =10000;
    IEPROC_EX_LIGHTFX_BEAM_CENTERY_DEFAULT =0;


    //---------------------------------------------

    IEPROC_EX_LIGHTFX_DOUBLEBEAM = 'Light Effect - Double Beam';
    IEPROC_EX_LIGHTFX_DOUBLEBEAM_ID = 0000012;

    IEPROC_EX_LIGHTFX_DOUBLEBEAM_COLOR = 'Color';
    IEPROC_EX_LIGHTFX_DOUBLEBEAM_COLOR_VTYPE= pt_int;
    IEPROC_EX_LIGHTFX_DOUBLEBEAM_COLOR_MIN =0;
    IEPROC_EX_LIGHTFX_DOUBLEBEAM_COLOR_MAX = MaxInt;
    IEPROC_EX_LIGHTFX_DOUBLEBEAM_COLOR_DEFAULT =16579839;

    IEPROC_EX_LIGHTFX_DOUBLEBEAM_LIGHTAMT = 'Light Amount';
    IEPROC_EX_LIGHTFX_DOUBLEBEAM_LIGHTAMT_VTYPE= pt_int;
    IEPROC_EX_LIGHTFX_DOUBLEBEAM_LIGHTAMT_MIN =0;
    IEPROC_EX_LIGHTFX_DOUBLEBEAM_LIGHTAMT_MAX = 100;
    IEPROC_EX_LIGHTFX_DOUBLEBEAM_LIGHTAMT_DEFAULT =50;

    IEPROC_EX_LIGHTFX_DOUBLEBEAM_BEAMSIZE = 'Beam Size';
    IEPROC_EX_LIGHTFX_DOUBLEBEAM_BEAMSIZE_VTYPE= pt_int;
    IEPROC_EX_LIGHTFX_DOUBLEBEAM_BEAMSIZE_MIN =1;
    IEPROC_EX_LIGHTFX_DOUBLEBEAM_BEAMSIZE_MAX =5000;
    IEPROC_EX_LIGHTFX_DOUBLEBEAM_BEAMSIZE_DEFAULT =50;

    IEPROC_EX_LIGHTFX_DOUBLEBEAM_OPENING = 'Opening';
    IEPROC_EX_LIGHTFX_DOUBLEBEAM_OPENING_VTYPE= pt_int;
    IEPROC_EX_LIGHTFX_DOUBLEBEAM_OPENING_MIN =0;
    IEPROC_EX_LIGHTFX_DOUBLEBEAM_OPENING_MAX =100;
    IEPROC_EX_LIGHTFX_DOUBLEBEAM_OPENING_DEFAULT =50;

    IEPROC_EX_LIGHTFX_DOUBLEBEAM_ANGLE = 'Angle';
    IEPROC_EX_LIGHTFX_DOUBLEBEAM_ANGLE_VTYPE= pt_int;
    IEPROC_EX_LIGHTFX_DOUBLEBEAM_ANGLE_MIN =0;
    IEPROC_EX_LIGHTFX_DOUBLEBEAM_ANGLE_MAX =360;
    IEPROC_EX_LIGHTFX_DOUBLEBEAM_ANGLE_DEFAULT =45;

    IEPROC_EX_LIGHTFX_DOUBLEBEAM_CENTERX = 'Center X';
    IEPROC_EX_LIGHTFX_DOUBLEBEAM_CENTERX_VTYPE= pt_int;
    IEPROC_EX_LIGHTFX_DOUBLEBEAM_CENTERX_MIN =0;
    IEPROC_EX_LIGHTFX_DOUBLEBEAM_CENTERX_MAX =10000;
    IEPROC_EX_LIGHTFX_DOUBLEBEAM_CENTERX_DEFAULT =0;

    IEPROC_EX_LIGHTFX_DOUBLEBEAM_CENTERY = 'Center Y';
    IEPROC_EX_LIGHTFX_DOUBLEBEAM_CENTERY_VTYPE= pt_int;
    IEPROC_EX_LIGHTFX_DOUBLEBEAM_CENTERY_MIN =0;
    IEPROC_EX_LIGHTFX_DOUBLEBEAM_CENTERY_MAX =10000;
    IEPROC_EX_LIGHTFX_DOUBLEBEAM_CENTERY_DEFAULT =0;


    //---------------------------------------------

    IEPROC_EX_IE_UNSHARPMASK = 'Unsharp Mask';
    IEPROC_EX_IE_UNSHARPMASK_ID = 1000001;

    IEPROC_EX_IE_UNSHARPMASK_AMOUNT = 'Amount';
    IEPROC_EX_IE_UNSHARPMASK_AMOUNT_VTYPE= pt_double;
    IEPROC_EX_IE_UNSHARPMASK_AMOUNT_MIN =0;
    IEPROC_EX_IE_UNSHARPMASK_AMOUNT_MAX =5;
    IEPROC_EX_IE_UNSHARPMASK_AMOUNT_DEFAULT =0;

    IEPROC_EX_IE_UNSHARPMASK_RADIUS = 'Radius';
    IEPROC_EX_IE_UNSHARPMASK_RADIUS_VTYPE= pt_double;
    IEPROC_EX_IE_UNSHARPMASK_RADIUS_MIN =1;
    IEPROC_EX_IE_UNSHARPMASK_RADIUS_MAX = 50;
    IEPROC_EX_IE_UNSHARPMASK_RADIUS_DEFAULT =1;

    IEPROC_EX_IE_UNSHARPMASK_THRESHOLD = 'Threshold';
    IEPROC_EX_IE_UNSHARPMASK_THRESHOLD_VTYPE= pt_double;
    IEPROC_EX_IE_UNSHARPMASK_THRESHOLD_MIN =0;
    IEPROC_EX_IE_UNSHARPMASK_THRESHOLD_MAX =1;
    IEPROC_EX_IE_UNSHARPMASK_THRESHOLD_DEFAULT =0;
    //---------------------------------------------

    IEPROC_EX_IE_BLUR = 'Gaussian Blur';
    IEPROC_EX_IE_BLUR_ID = 1000002;

    IEPROC_EX_IE_BLUR_RADIUS = 'Radius';
    IEPROC_EX_IE_BLUR_RADIUS_VTYPE= pt_double;
    IEPROC_EX_IE_BLUR_RADIUS_MIN =0;
    IEPROC_EX_IE_BLUR_RADIUS_MAX = 100;
    IEPROC_EX_IE_BLUR_RADIUS_DEFAULT =0;
    //---------------------------------------------

    IEPROC_EX_IE_HSLVAR = 'HSL';
    IEPROC_EX_IE_HSLVAR_ID = 1000003;

    IEPROC_EX_IE_HSLVAR_HUE = 'Hue';
    IEPROC_EX_IE_HSLVAR_HUE_VTYPE= pt_Int;
    IEPROC_EX_IE_HSLVAR_HUE_MIN =0;
    IEPROC_EX_IE_HSLVAR_HUE_MAX =360;
    IEPROC_EX_IE_HSLVAR_HUE_DEFAULT =0;

    IEPROC_EX_IE_HSLVAR_SAT = 'Saturation';
    IEPROC_EX_IE_HSLVAR_SAT_VTYPE= pt_Int;
    IEPROC_EX_IE_HSLVAR_SAT_MIN =-100;
    IEPROC_EX_IE_HSLVAR_SAT_MAX = 100;
    IEPROC_EX_IE_HSLVAR_SAT_DEFAULT =0;

    IEPROC_EX_IE_HSLVAR_LUM = 'Luminance';
    IEPROC_EX_IE_HSLVAR_LUM_VTYPE= pt_Int;
    IEPROC_EX_IE_HSLVAR_LUM_MIN =-100;
    IEPROC_EX_IE_HSLVAR_LUM_MAX = 100;
    IEPROC_EX_IE_HSLVAR_LUM_DEFAULT =0;

     //---------------------------------------------

    IEPROC_EX_IE_HSVVAR = 'HSV';
    IEPROC_EX_IE_HSVVAR_ID = 1000004;

    IEPROC_EX_IE_HSVVAR_HUE = 'Hue';
    IEPROC_EX_IE_HSVVAR_HUE_VTYPE= pt_Int;
    IEPROC_EX_IE_HSVVAR_HUE_MIN =0;
    IEPROC_EX_IE_HSVVAR_HUE_MAX =360;
    IEPROC_EX_IE_HSVVAR_HUE_DEFAULT =0;

    IEPROC_EX_IE_HSVVAR_SAT = 'Saturation';
    IEPROC_EX_IE_HSVVAR_SAT_VTYPE= pt_Int;
    IEPROC_EX_IE_HSVVAR_SAT_MIN =-100;
    IEPROC_EX_IE_HSVVAR_SAT_MAX = 100;
    IEPROC_EX_IE_HSVVAR_SAT_DEFAULT =0;

    IEPROC_EX_IE_HSVVAR_VALUE = 'Value';
    IEPROC_EX_IE_HSVVAR_VALUE_VTYPE= pt_Int;
    IEPROC_EX_IE_HSVVAR_VALUE_MIN =-100;
    IEPROC_EX_IE_HSVVAR_VALUE_MAX = 100;
    IEPROC_EX_IE_HSVVAR_VALUE_DEFAULT =0;
    //---------------------------------------------

    IEPROC_EX_IE_NEGATIVE = 'Negative';
    IEPROC_EX_IE_NEGATIVE_ID = 1000005;

     //---------------------------------------------

    IEPROC_EX_IE_INTENSITYRGBALL = 'Intensity RGB';
    IEPROC_EX_IE_INTENSITYRGBALL_ID = 1000006;

    IEPROC_EX_IE_INTENSITYRGBALL_INTENSITYRED = 'Intensity Red';
    IEPROC_EX_IE_INTENSITYRGBALL_INTENSITYRED_VTYPE= pt_Int;
    IEPROC_EX_IE_INTENSITYRGBALL_INTENSITYRED_MIN =-255;
    IEPROC_EX_IE_INTENSITYRGBALL_INTENSITYRED_MAX =255;
    IEPROC_EX_IE_INTENSITYRGBALL_INTENSITYRED_DEFAULT =0;

    IEPROC_EX_IE_INTENSITYRGBALL_INTENSITYGREEN = 'Intensity Green';
    IEPROC_EX_IE_INTENSITYRGBALL_INTENSITYGREEN_VTYPE= pt_Int;
    IEPROC_EX_IE_INTENSITYRGBALL_INTENSITYGREEN_MIN =-255;
    IEPROC_EX_IE_INTENSITYRGBALL_INTENSITYGREEN_MAX = 255;
    IEPROC_EX_IE_INTENSITYRGBALL_INTENSITYGREEN_DEFAULT =0;

    IEPROC_EX_IE_INTENSITYRGBALL_INTENSITYBLUE = 'Intensity Blue';
    IEPROC_EX_IE_INTENSITYRGBALL_INTENSITYBLUE_VTYPE= pt_Int;
    IEPROC_EX_IE_INTENSITYRGBALL_INTENSITYBLUE_MIN =-255;
    IEPROC_EX_IE_INTENSITYRGBALL_INTENSITYBLUE_MAX = 255;
    IEPROC_EX_IE_INTENSITYRGBALL_INTENSITYBLUE_DEFAULT =0;

      //---------------------------------------------

    IEPROC_EX_IE_INTENSITY = 'Intensity';
    IEPROC_EX_IE_INTENSITY_ID = 1000007;

    IEPROC_EX_IE_INTENSITY_LOLIMIT = 'Low Limit';
    IEPROC_EX_IE_INTENSITY_LOLIMIT_VTYPE= pt_Int;
    IEPROC_EX_IE_INTENSITY_LOLIMIT_MIN =0;
    IEPROC_EX_IE_INTENSITY_LOLIMIT_MAX =255;
    IEPROC_EX_IE_INTENSITY_LOLIMIT_DEFAULT =0;

    IEPROC_EX_IE_INTENSITY_HILIMIT = 'High Limit';
    IEPROC_EX_IE_INTENSITY_HILIMIT_VTYPE= pt_Int;
    IEPROC_EX_IE_INTENSITY_HILIMIT_MIN =0;
    IEPROC_EX_IE_INTENSITY_HILIMIT_MAX = 255;
    IEPROC_EX_IE_INTENSITY_HILIMIT_DEFAULT =0;

    IEPROC_EX_IE_INTENSITY_CHANGE = 'Change';
    IEPROC_EX_IE_INTENSITY_CHANGE_VTYPE= pt_Int;
    IEPROC_EX_IE_INTENSITY_CHANGE_MIN =-255;
    IEPROC_EX_IE_INTENSITY_CHANGE_MAX = 255;
    IEPROC_EX_IE_INTENSITY_CHANGE_DEFAULT =-255;

    IEPROC_EX_IE_INTENSITY_USEAVERAGERGB = 'use Average RGB';
    IEPROC_EX_IE_INTENSITY_USEAVERAGERGB_VTYPE= pt_boolean;
    IEPROC_EX_IE_INTENSITY_USEAVERAGERGB_MIN = FALSE;
    IEPROC_EX_IE_INTENSITY_USEAVERAGERGB_MAX = TRUE;
    IEPROC_EX_IE_INTENSITY_USEAVERAGERGB_DEFAULT = TRUE;

    IEPROC_EX_IE_INTENSITY_DORED = 'Include Red';
    IEPROC_EX_IE_INTENSITY_DORED_VTYPE= pt_boolean;
    IEPROC_EX_IE_INTENSITY_DORED_MIN = FALSE;
    IEPROC_EX_IE_INTENSITY_DORED_MAX = TRUE;
    IEPROC_EX_IE_INTENSITY_DORED_DEFAULT = TRUE;

    IEPROC_EX_IE_INTENSITY_DOGREEN = 'Include Green';
    IEPROC_EX_IE_INTENSITY_DOGREEN_VTYPE= pt_boolean;
    IEPROC_EX_IE_INTENSITY_DOGREEN_MIN = FALSE;
    IEPROC_EX_IE_INTENSITY_DOGREEN_MAX = TRUE;
    IEPROC_EX_IE_INTENSITY_DOGREEN_DEFAULT = TRUE;

    IEPROC_EX_IE_INTENSITY_DOBLUE = 'Include Blue';
    IEPROC_EX_IE_INTENSITY_DOBLUE_VTYPE= pt_boolean;
    IEPROC_EX_IE_INTENSITY_DOBLUE_MIN = FALSE;
    IEPROC_EX_IE_INTENSITY_DOBLUE_MAX = TRUE;
    IEPROC_EX_IE_INTENSITY_DOBLUE_DEFAULT = TRUE;

    //---------------------------------------------

    IEPROC_EX_IE_CONTRAST = 'Contrast';
    IEPROC_EX_IE_CONTRAST_ID = 1000008;

    IEPROC_EX_IE_CONTRAST_AMOUNT = 'Amount';
    IEPROC_EX_IE_CONTRAST_AMOUNT_VTYPE= pt_double;
    IEPROC_EX_IE_CONTRAST_AMOUNT_MIN =-100;
    IEPROC_EX_IE_CONTRAST_AMOUNT_MAX =100;
    IEPROC_EX_IE_CONTRAST_AMOUNT_DEFAULT =-100;

    //---------------------------------------------

    IEPROC_EX_IE_CONTRAST2 = 'Contrast2';
    IEPROC_EX_IE_CONTRAST2_ID = 1000009;

    IEPROC_EX_IE_CONTRAST2_AMOUNT = 'Amount';
    IEPROC_EX_IE_CONTRAST2_AMOUNT_VTYPE= pt_double;
    IEPROC_EX_IE_CONTRAST2_AMOUNT_MIN =0;
    IEPROC_EX_IE_CONTRAST2_AMOUNT_MAX =1;
    IEPROC_EX_IE_CONTRAST2_AMOUNT_DEFAULT =0;

    //---------------------------------------------
    //Change, Midpoint:integer; DoRed, DoGreen, DoBlue:boolean
    IEPROC_EX_IE_CONTRAST3 = 'Contrast3';
    IEPROC_EX_IE_CONTRAST3_ID = 1000010;

    IEPROC_EX_IE_CONTRAST3_CHANGE = 'Change';
    IEPROC_EX_IE_CONTRAST3_CHANGE_VTYPE= pt_Int;
    IEPROC_EX_IE_CONTRAST3_CHANGE_MIN =-255;
    IEPROC_EX_IE_CONTRAST3_CHANGE_MAX =255;
    IEPROC_EX_IE_CONTRAST3_CHANGE_DEFAULT =-255;

    IEPROC_EX_IE_CONTRAST3_MIDPOINT = 'Mid Point';
    IEPROC_EX_IE_CONTRAST3_MIDPOINT_VTYPE= pt_Int;
    IEPROC_EX_IE_CONTRAST3_MIDPOINT_MIN =-100;
    IEPROC_EX_IE_CONTRAST3_MIDPOINT_MAX =100;
    IEPROC_EX_IE_CONTRAST3_MIDPOINT_DEFAULT =-100;

    IEPROC_EX_IE_CONTRAST3_DORED = 'Include Red';
    IEPROC_EX_IE_CONTRAST3_DORED_VTYPE= pt_boolean;
    IEPROC_EX_IE_CONTRAST3_DORED_MIN = FALSE;
    IEPROC_EX_IE_CONTRAST3_DORED_MAX = TRUE;
    IEPROC_EX_IE_CONTRAST3_DORED_DEFAULT = TRUE;

    IEPROC_EX_IE_CONTRAST3_DOGREEN = 'Include Green';
    IEPROC_EX_IE_CONTRAST3_DOGREEN_VTYPE= pt_boolean;
    IEPROC_EX_IE_CONTRAST3_DOGREEN_MIN = FALSE;
    IEPROC_EX_IE_CONTRAST3_DOGREEN_MAX = TRUE;
    IEPROC_EX_IE_CONTRAST3_DOGREEN_DEFAULT = TRUE;

    IEPROC_EX_IE_CONTRAST3_DOBLUE = 'Include Blue';
    IEPROC_EX_IE_CONTRAST3_DOBLUE_VTYPE= pt_boolean;
    IEPROC_EX_IE_CONTRAST3_DOBLUE_MIN = FALSE;
    IEPROC_EX_IE_CONTRAST3_DOBLUE_MAX = TRUE;
    IEPROC_EX_IE_CONTRAST3_DOBLUE_DEFAULT = TRUE;


    //---------------------------------------------
    //Change, Midpoint:integer; DoRed, DoGreen, DoBlue:boolean
    IEPROC_EX_IE_GAMMACORRECT = 'Gamma Correction';
    IEPROC_EX_IE_GAMMACORRECT_ID = 1000011;

    IEPROC_EX_IE_GAMMACORRECT_GAMMA = 'Gamma';
    IEPROC_EX_IE_GAMMACORRECT_GAMMA_VTYPE= pt_double;
    IEPROC_EX_IE_GAMMACORRECT_GAMMA_MIN =0.02;
    IEPROC_EX_IE_GAMMACORRECT_GAMMA_MAX =10;
    IEPROC_EX_IE_GAMMACORRECT_GAMMA_DEFAULT =1;

    IEPROC_EX_IE_GAMMACORRECT_DORED = 'Include Red';
    IEPROC_EX_IE_GAMMACORRECT_DORED_VTYPE= pt_boolean;
    IEPROC_EX_IE_GAMMACORRECT_DORED_MIN = FALSE;
    IEPROC_EX_IE_GAMMACORRECT_DORED_MAX = TRUE;
    IEPROC_EX_IE_GAMMACORRECT_DORED_DEFAULT = TRUE;

    IEPROC_EX_IE_GAMMACORRECT_DOGREEN = 'Include Green';
    IEPROC_EX_IE_GAMMACORRECT_DOGREEN_VTYPE= pt_boolean;
    IEPROC_EX_IE_GAMMACORRECT_DOGREEN_MIN = FALSE;
    IEPROC_EX_IE_GAMMACORRECT_DOGREEN_MAX = TRUE;
    IEPROC_EX_IE_GAMMACORRECT_DOGREEN_DEFAULT = TRUE;

    IEPROC_EX_IE_GAMMACORRECT_DOBLUE = 'Include Blue';
    IEPROC_EX_IE_GAMMACORRECT_DOBLUE_VTYPE= pt_boolean;
    IEPROC_EX_IE_GAMMACORRECT_DOBLUE_MIN = FALSE;
    IEPROC_EX_IE_GAMMACORRECT_DOBLUE_MAX = TRUE;
    IEPROC_EX_IE_GAMMACORRECT_DOBLUE_DEFAULT = TRUE;
     //---------------------------------------------

    IEPROC_EX_IE_AUTOSHARP = 'Auto-Sharpness';
    IEPROC_EX_IE_AUTOSHARP_ID = 1000012;

    IEPROC_EX_IE_AUTOSHARP_INTENSITY = 'Intensity';
    IEPROC_EX_IE_AUTOSHARP_INTENSITY_VTYPE= pt_Int;
    IEPROC_EX_IE_AUTOSHARP_INTENSITY_MIN =0;
    IEPROC_EX_IE_AUTOSHARP_INTENSITY_MAX =100;
    IEPROC_EX_IE_AUTOSHARP_INTENSITY_DEFAULT =0;

    IEPROC_EX_IE_AUTOSHARP_RATE = 'Rate';
    IEPROC_EX_IE_AUTOSHARP_RATE_VTYPE= pt_double;
    IEPROC_EX_IE_AUTOSHARP_RATE_MIN =0;
    IEPROC_EX_IE_AUTOSHARP_RATE_MAX =1;
    IEPROC_EX_IE_AUTOSHARP_RATE_DEFAULT =0;
    //AutoSharp(Intensity:integer=68; rate:double=0.035);


     //---------------------------------------------

    IEPROC_EX_IE_COLORIZE = 'Colorize';
    IEPROC_EX_IE_COLORIZE_ID = 1000013;

    IEPROC_EX_IE_COLORIZE_HUE = 'Hue';
    IEPROC_EX_IE_COLORIZE_HUE_VTYPE= pt_Int;
    IEPROC_EX_IE_COLORIZE_HUE_MIN =0;
    IEPROC_EX_IE_COLORIZE_HUE_MAX =360;
    IEPROC_EX_IE_COLORIZE_HUE_DEFAULT =0;

    IEPROC_EX_IE_COLORIZE_SAT = 'Saturation';
    IEPROC_EX_IE_COLORIZE_SAT_VTYPE= pt_Int;
    IEPROC_EX_IE_COLORIZE_SAT_MIN =0;
    IEPROC_EX_IE_COLORIZE_SAT_MAX = 100;
    IEPROC_EX_IE_COLORIZE_SAT_DEFAULT =100;

    IEPROC_EX_IE_COLORIZE_LUM = 'Luminosity';
    IEPROC_EX_IE_COLORIZE_LUM_VTYPE= pt_double;
    IEPROC_EX_IE_COLORIZE_LUM_MIN =0;
    IEPROC_EX_IE_COLORIZE_LUM_MAX = 1;
    IEPROC_EX_IE_COLORIZE_LUM_DEFAULT =1;
    //hue:integer; saturation:integer; luminosity:double


    //---------------------------------------------
    IEPROC_EX_IE_BRIGHTNESS_CONTRAST_SATURATION = 'Brightness, Contrast, Saturation';
    IEPROC_EX_IE_BRIGHTNESS_CONTRAST_SATURATION_ID = 1000014;

    IEPROC_EX_IE_BRIGHTNESS_CONTRAST_SATURATION_BRIGHTNESS = 'Brightness';
    IEPROC_EX_IE_BRIGHTNESS_CONTRAST_SATURATION_BRIGHTNESS_VTYPE= pt_Int;
    IEPROC_EX_IE_BRIGHTNESS_CONTRAST_SATURATION_BRIGHTNESS_MIN =-100;
    IEPROC_EX_IE_BRIGHTNESS_CONTRAST_SATURATION_BRIGHTNESS_MAX =512;
    IEPROC_EX_IE_BRIGHTNESS_CONTRAST_SATURATION_BRIGHTNESS_DEFAULT =0;

    IEPROC_EX_IE_BRIGHTNESS_CONTRAST_SATURATION_CONTRAST = 'Contrast';
    IEPROC_EX_IE_BRIGHTNESS_CONTRAST_SATURATION_CONTRAST_VTYPE= pt_Int;
    IEPROC_EX_IE_BRIGHTNESS_CONTRAST_SATURATION_CONTRAST_MIN =-100;
    IEPROC_EX_IE_BRIGHTNESS_CONTRAST_SATURATION_CONTRAST_MAX = 100;
    IEPROC_EX_IE_BRIGHTNESS_CONTRAST_SATURATION_CONTRAST_DEFAULT =0;

    IEPROC_EX_IE_BRIGHTNESS_CONTRAST_SATURATION_SAT = 'Saturation';
    IEPROC_EX_IE_BRIGHTNESS_CONTRAST_SATURATION_SAT_VTYPE= pt_Int;
    IEPROC_EX_IE_BRIGHTNESS_CONTRAST_SATURATION_SAT_MIN =0;
    IEPROC_EX_IE_BRIGHTNESS_CONTRAST_SATURATION_SAT_MAX = 512;
    IEPROC_EX_IE_BRIGHTNESS_CONTRAST_SATURATION_SAT_DEFAULT =0;
    // AdjustBrightnessContrastSaturation(Brightness, Contrast, Saturation:integer);

     //---------------------------------------------
    IEPROC_EX_IE_ADJUST_TINT = 'Adjust Tint';
    IEPROC_EX_IE_ADJUST_TINT_ID = 1000015;

    IEPROC_EX_IE_ADJUST_TINT_AMOUNT = 'Amount';
    IEPROC_EX_IE_ADJUST_TINT_AMOUNT_VTYPE= pt_Int;
    IEPROC_EX_IE_ADJUST_TINT_AMOUNT_MIN =-180;
    IEPROC_EX_IE_ADJUST_TINT_AMOUNT_MAX =180;
    IEPROC_EX_IE_ADJUST_TINT_AMOUNT_DEFAULT =0;

         //---------------------------------------------
    IEPROC_EX_IE_ADJUST_SATURATION = 'Adjust Saturation';
    IEPROC_EX_IE_ADJUST_SATURATION_ID = 1000016;

    IEPROC_EX_IE_ADJUST_SATURATION_AMOUNT = 'Amount';
    IEPROC_EX_IE_ADJUST_SATURATION_AMOUNT_VTYPE= pt_Int;
    IEPROC_EX_IE_ADJUST_SATURATION_AMOUNT_MIN =-100;
    IEPROC_EX_IE_ADJUST_SATURATION_AMOUNT_MAX =100;
    IEPROC_EX_IE_ADJUST_SATURATION_AMOUNT_DEFAULT =0;

    //---------------------------------------------
    IEPROC_EX_IE_ADJUST_TEMPERATURE = 'Adjust Temperature';
    IEPROC_EX_IE_ADJUST_TEMPERATURE_ID = 1000017;

    IEPROC_EX_IE_ADJUST_TEMPERATURE_AMOUNT = 'Amount';
    IEPROC_EX_IE_ADJUST_TEMPERATURE_AMOUNT_VTYPE= pt_Int;
    IEPROC_EX_IE_ADJUST_TEMPERATURE_AMOUNT_MIN =1000;
    IEPROC_EX_IE_ADJUST_TEMPERATURE_AMOUNT_MAX =40000;
    IEPROC_EX_IE_ADJUST_TEMPERATURE_AMOUNT_DEFAULT =7100;

      //---------------------------------------------

    IEPROC_EX_IE_ADJUST_LUM_SAT_HISTOGRAM = 'Luminosity, Saturation';
    IEPROC_EX_IE_ADJUST_LUM_SAT_HISTOGRAM_ID = 1000018;

    IEPROC_EX_IE_ADJUST_LUM_SAT_HISTOGRAM_LUM = 'Luminosity';
    IEPROC_EX_IE_ADJUST_LUM_SAT_HISTOGRAM_LUM_VTYPE= pt_double;
    IEPROC_EX_IE_ADJUST_LUM_SAT_HISTOGRAM_LUM_MIN =0;
    IEPROC_EX_IE_ADJUST_LUM_SAT_HISTOGRAM_LUM_MAX = 1;
    IEPROC_EX_IE_ADJUST_LUM_SAT_HISTOGRAM_LUM_DEFAULT =0;

    IEPROC_EX_IE_ADJUST_LUM_SAT_HISTOGRAM_SAT = 'Saturation';
    IEPROC_EX_IE_ADJUST_LUM_SAT_HISTOGRAM_SAT_VTYPE= pt_double;
    IEPROC_EX_IE_ADJUST_LUM_SAT_HISTOGRAM_SAT_MIN =0;
    IEPROC_EX_IE_ADJUST_LUM_SAT_HISTOGRAM_SAT_MAX = 1;
    IEPROC_EX_IE_ADJUST_LUM_SAT_HISTOGRAM_SAT_DEFAULT =0;

    //---------------------------------------------

    IEPROC_EX_IE_WHITEBALANCE_COEF = 'White Balance Coefs';
    IEPROC_EX_IE_WHITEBALANCE_COEF_ID = 1000019;

    IEPROC_EX_IE_WHITEBALANCE_COEF_RED = 'Red';
    IEPROC_EX_IE_WHITEBALANCE_COEF_RED_VTYPE = pt_double;
    IEPROC_EX_IE_WHITEBALANCE_COEF_RED_MIN =0;
    IEPROC_EX_IE_WHITEBALANCE_COEF_RED_MAX = 1.3;
    IEPROC_EX_IE_WHITEBALANCE_COEF_RED_DEFAULT =1;

    IEPROC_EX_IE_WHITEBALANCE_COEF_GREEN = 'Green';
    IEPROC_EX_IE_WHITEBALANCE_COEF_GREEN_VTYPE = pt_double;
    IEPROC_EX_IE_WHITEBALANCE_COEF_GREEN_MIN =0;
    IEPROC_EX_IE_WHITEBALANCE_COEF_GREEN_MAX = 1.3;
    IEPROC_EX_IE_WHITEBALANCE_COEF_GREEN_DEFAULT =1;

    IEPROC_EX_IE_WHITEBALANCE_COEF_BLUE = 'Blue';
    IEPROC_EX_IE_WHITEBALANCE_COEF_BLUE_VTYPE = pt_double;
    IEPROC_EX_IE_WHITEBALANCE_COEF_BLUE_MIN =0;
    IEPROC_EX_IE_WHITEBALANCE_COEF_BLUE_MAX = 1.3;
    IEPROC_EX_IE_WHITEBALANCE_COEF_BLUE_DEFAULT =1;

    //---------------------------------------------

    IEPROC_EX_IE_WHITEBALANCE_GRAYWORLD = 'White Balance GrayWorld';
    IEPROC_EX_IE_WHITEBALANCE_GRAYWORLD_ID = 1000020;

    //---------------------------------------------

    IEPROC_EX_IE_WHITEBALANCE_WHITEAT = 'White Balance At';
    IEPROC_EX_IE_WHITEBALANCE_WHITEAT_ID = 1000021;

    IEPROC_EX_IE_WHITEBALANCE_WHITEAT_WHITEX = 'White X';
    IEPROC_EX_IE_WHITEBALANCE_WHITEAT_WHITEX_VTYPE = pt_Int;
    IEPROC_EX_IE_WHITEBALANCE_WHITEAT_WHITEX_MIN =0;
    IEPROC_EX_IE_WHITEBALANCE_WHITEAT_WHITEX_MAX = 20000;
    IEPROC_EX_IE_WHITEBALANCE_WHITEAT_WHITEX_DEFAULT =0;

    IEPROC_EX_IE_WHITEBALANCE_WHITEAT_WHITEY = 'White Y';
    IEPROC_EX_IE_WHITEBALANCE_WHITEAT_WHITEY_VTYPE = pt_Int;
    IEPROC_EX_IE_WHITEBALANCE_WHITEAT_WHITEY_MIN =0;
    IEPROC_EX_IE_WHITEBALANCE_WHITEAT_WHITEY_MAX = 20000;
    IEPROC_EX_IE_WHITEBALANCE_WHITEAT_WHITEY_DEFAULT =0;

    //---------------------------------------------

    IEPROC_EX_IE_WHITEBALANCE_AUTOWHITE = 'Auto White Balance';
    IEPROC_EX_IE_WHITEBALANCE_AUTOWHITE_ID = 1000022;

    //---------------------------------------------
    {
    procedure AutoImageEnhance1(SubsampledSize: Integer = 60; Slope: Integer = 20;
                                Cut: Integer = 25; Neighbour: Integer = 2);
    }
    IEPROC_EX_IE_AUTOIMAGEENHANCE1 = 'Auto Enhance Normal';
    IEPROC_EX_IE_AUTOIMAGEENHANCE1_ID = 1000023;

    IEPROC_EX_IE_AUTOIMAGEENHANCE1_SUBSAMPLEDSIZE = 'Subsample Size';   //1-infinite def 60
    IEPROC_EX_IE_AUTOIMAGEENHANCE1_SUBSAMPLEDSIZE_VTYPE = pt_Int;
    IEPROC_EX_IE_AUTOIMAGEENHANCE1_SUBSAMPLEDSIZE_MIN = 20;
    IEPROC_EX_IE_AUTOIMAGEENHANCE1_SUBSAMPLEDSIZE_MAX = 500;
    IEPROC_EX_IE_AUTOIMAGEENHANCE1_SUBSAMPLEDSIZE_DEFAULT = 45;

    IEPROC_EX_IE_AUTOIMAGEENHANCE1_SLOPE = 'Slope';            //slope  //0 to 90  def 20
    IEPROC_EX_IE_AUTOIMAGEENHANCE1_SLOPE_VTYPE = pt_Int;
    IEPROC_EX_IE_AUTOIMAGEENHANCE1_SLOPE_MIN = 0;
    IEPROC_EX_IE_AUTOIMAGEENHANCE1_SLOPE_MAX = 90;
    IEPROC_EX_IE_AUTOIMAGEENHANCE1_SLOPE_DEFAULT = 20;

    IEPROC_EX_IE_AUTOIMAGEENHANCE1_CUT = 'Cut';         //cut    //0 to 100 def 25
    IEPROC_EX_IE_AUTOIMAGEENHANCE1_CUT_VTYPE = pt_Int;
    IEPROC_EX_IE_AUTOIMAGEENHANCE1_CUT_MIN = 0;
    IEPROC_EX_IE_AUTOIMAGEENHANCE1_CUT_MAX = 100;
    IEPROC_EX_IE_AUTOIMAGEENHANCE1_CUT_DEFAULT = 60;


    IEPROC_EX_IE_AUTOIMAGEENHANCE1_NEIGHBOUR = 'Neighbour';        //neighbour  //1 to infinite def 2
    IEPROC_EX_IE_AUTOIMAGEENHANCE1_NEIGHBOUR_VTYPE = pt_Int;
    IEPROC_EX_IE_AUTOIMAGEENHANCE1_NEIGHBOUR_MIN = 1;
    IEPROC_EX_IE_AUTOIMAGEENHANCE1_NEIGHBOUR_MAX = 20;
    IEPROC_EX_IE_AUTOIMAGEENHANCE1_NEIGHBOUR_DEFAULT = 3;




    //---------------------------------------------
        {
    procedure AutoImageEnhance2(ScaleCount: Integer = 3; ScaleCurve: Integer = 2;
                                Variance: Double = 1.8; ScaleHigh: Integer = 200; Luminance: Boolean = True);
    }

    IEPROC_EX_IE_AUTOIMAGEENHANCE2 = 'Auto Enhance 2';
    IEPROC_EX_IE_AUTOIMAGEENHANCE2_ID = 1000024;

    IEPROC_EX_IE_AUTOIMAGEENHANCE2_SCALECOUNT = 'Scale Count';
    IEPROC_EX_IE_AUTOIMAGEENHANCE2_SCALECOUNT_VTYPE = pt_Int;
    IEPROC_EX_IE_AUTOIMAGEENHANCE2_SCALECOUNT_MIN = 1;
    IEPROC_EX_IE_AUTOIMAGEENHANCE2_SCALECOUNT_MAX = 10;
    IEPROC_EX_IE_AUTOIMAGEENHANCE2_SCALECOUNT_DEFAULT = 3;


    IEPROC_EX_IE_AUTOIMAGEENHANCE2_SCALECURVE = 'Scale Curve';
    IEPROC_EX_IE_AUTOIMAGEENHANCE2_SCALECURVE_VTYPE = pt_Int;
    IEPROC_EX_IE_AUTOIMAGEENHANCE2_SCALECURVE_MIN = 0;
    IEPROC_EX_IE_AUTOIMAGEENHANCE2_SCALECURVE_MAX = 2;
    IEPROC_EX_IE_AUTOIMAGEENHANCE2_SCALECURVE_DEFAULT = 2;


    IEPROC_EX_IE_AUTOIMAGEENHANCE2_VARIANCE = 'Variance';
    IEPROC_EX_IE_AUTOIMAGEENHANCE2_VARIANCE_VTYPE = pt_double;
    IEPROC_EX_IE_AUTOIMAGEENHANCE2_VARIANCE_MIN = 0;
    IEPROC_EX_IE_AUTOIMAGEENHANCE2_VARIANCE_MAX = 10;
    IEPROC_EX_IE_AUTOIMAGEENHANCE2_VARIANCE_DEFAULT = 1.8;


    IEPROC_EX_IE_AUTOIMAGEENHANCE2_SCALEHIGH = 'Scale High';
    IEPROC_EX_IE_AUTOIMAGEENHANCE2_SCALEHIGH_VTYPE = pt_Int;
    IEPROC_EX_IE_AUTOIMAGEENHANCE2_SCALEHIGH_MIN = 16;
    IEPROC_EX_IE_AUTOIMAGEENHANCE2_SCALEHIGH_MAX = 250;
    IEPROC_EX_IE_AUTOIMAGEENHANCE2_SCALEHIGH_DEFAULT = 200;

    IEPROC_EX_IE_AUTOIMAGEENHANCE2_LUMINANCE = 'Luminance';
    IEPROC_EX_IE_AUTOIMAGEENHANCE2_LUMINANCE_VTYPE = pt_boolean;
    IEPROC_EX_IE_AUTOIMAGEENHANCE2_LUMINANCE_MIN = FALSE;
    IEPROC_EX_IE_AUTOIMAGEENHANCE2_LUMINANCE_MAX = TRUE;
    IEPROC_EX_IE_AUTOIMAGEENHANCE2_LUMINANCE_DEFAULT = TRUE;


    //---------------------------------------------
     //procedure AutoImageEnhance3(Gamma: Double = 0.35; Saturation: Integer = 80);
    IEPROC_EX_IE_AUTOIMAGEENHANCE3 = 'Auto Enhance Tone-Mapping';
    IEPROC_EX_IE_AUTOIMAGEENHANCE3_ID = 1000025;

    IEPROC_EX_IE_AUTOIMAGEENHANCE3_GAMMA = 'Gamma';
    IEPROC_EX_IE_AUTOIMAGEENHANCE3_GAMMA_VTYPE = pt_double;
    IEPROC_EX_IE_AUTOIMAGEENHANCE3_GAMMA_MIN = 0.1;
    IEPROC_EX_IE_AUTOIMAGEENHANCE3_GAMMA_MAX = 0.8;
    IEPROC_EX_IE_AUTOIMAGEENHANCE3_GAMMA_DEFAULT = 0.35;


    IEPROC_EX_IE_AUTOIMAGEENHANCE3_SATURATION = 'Saturation';
    IEPROC_EX_IE_AUTOIMAGEENHANCE3_SATURATION_VTYPE = pt_int;
    IEPROC_EX_IE_AUTOIMAGEENHANCE3_SATURATION_MIN = 50;
    IEPROC_EX_IE_AUTOIMAGEENHANCE3_SATURATION_MAX = 100;
    IEPROC_EX_IE_AUTOIMAGEENHANCE3_SATURATION_DEFAULT = 80;

    //-----------------------------------------------------------------

    IEPROC_EX_IE_MEDIANSHARPEN = 'Median Sharpen';
    IEPROC_EX_IE_MEDIANSHARPEN_ID = 1000026;

    IEPROC_EX_IE_MEDIANSHARPEN_WINDOW = 'Window';
    IEPROC_EX_IE_MEDIANSHARPEN_WINDOW_VTYPE = pt_int;
    IEPROC_EX_IE_MEDIANSHARPEN_WINDOW_MIN = 2;
    IEPROC_EX_IE_MEDIANSHARPEN_WINDOW_MAX = 16;
    IEPROC_EX_IE_MEDIANSHARPEN_WINDOW_DEFAULT = 2;

    IEPROC_EX_IE_MEDIANSHARPEN_MULTIPLIER = 'Multiplier';
    IEPROC_EX_IE_MEDIANSHARPEN_MULTIPLIER_VTYPE = pt_int;
    IEPROC_EX_IE_MEDIANSHARPEN_MULTIPLIER_MIN = 1;
    IEPROC_EX_IE_MEDIANSHARPEN_MULTIPLIER_MAX = 50;
    IEPROC_EX_IE_MEDIANSHARPEN_MULTIPLIER_DEFAULT = 1;

    //-----------------------------------------------------------------

    IEPROC_EX_IE_SHARPEN = 'Sharpen';
    IEPROC_EX_IE_SHARPEN_ID = 1000027;

    IEPROC_EX_IE_SHARPEN_AMOUNT = 'Amount';
    IEPROC_EX_IE_SHARPEN_AMOUNT_VTYPE = pt_int;
    IEPROC_EX_IE_SHARPEN_AMOUNT_MIN = 1;
    IEPROC_EX_IE_SHARPEN_AMOUNT_MAX = 50;
    IEPROC_EX_IE_SHARPEN_AMOUNT_DEFAULT = 1;


    IEPROC_EX_IE_SHARPEN_WINDOW = 'Window';
    IEPROC_EX_IE_SHARPEN_WINDOW_VTYPE = pt_int;
    IEPROC_EX_IE_SHARPEN_WINDOW_MIN = 2;
    IEPROC_EX_IE_SHARPEN_WINDOW_MAX = 16;
    IEPROC_EX_IE_SHARPEN_WINDOW_DEFAULT = 2;

    //-----------------------------------------------------------------

    IEPROC_EX_IE_MEDIAN = 'Median';
    IEPROC_EX_IE_MEDIAN_ID = 1000028;

    IEPROC_EX_IE_MEDIAN_WINDOW = 'Window';
    IEPROC_EX_IE_MEDIAN_WINDOW_VTYPE = pt_int;
    IEPROC_EX_IE_MEDIAN_WINDOW_MIN = 2;
    IEPROC_EX_IE_MEDIAN_WINDOW_MAX = 16;
    IEPROC_EX_IE_MEDIAN_WINDOW_DEFAULT = 2;

    IEPROC_EX_IE_MEDIAN_THRESHOLD = 'Threshold';
    IEPROC_EX_IE_MEDIAN_THRESHOLD_VTYPE = pt_int;
    IEPROC_EX_IE_MEDIAN_THRESHOLD_MIN = 1;
    IEPROC_EX_IE_MEDIAN_THRESHOLD_MAX = 100;
    IEPROC_EX_IE_MEDIAN_THRESHOLD_DEFAULT = 50;
    //-----------------------------------------------------------------------



    IEPROC_EX_IE_FINDEDGES = 'Find Edges';
    IEPROC_EX_IE_FINDEDGES_ID = 1000029;

    IEPROC_EX_IE_FINDEDGES_KERNELSIZE = 'Kernel Size';
    IEPROC_EX_IE_FINDEDGES_KERNELSIZE_VTYPE = pt_int;
    IEPROC_EX_IE_FINDEDGES_KERNELSIZE_MIN = 0;
    IEPROC_EX_IE_FINDEDGES_KERNELSIZE_MAX = 1;
    IEPROC_EX_IE_FINDEDGES_KERNELSIZE_DEFAULT = 0;
    //-----------------------------------------------------------------


implementation

end.
